### ISSUE TITLE
together.js and KAlite

### ISSUE THREAD

**Issue by jonschull** [learningequality/ka-lite#1079]
My team is  working on connected coaching:  a remote coach interacting via video and pointing with a student working on KALite.

We've implemented this in several ways (hangouts, frames, etc.) but they've proven brittle, especially in the context of school system internet security.

We do find that Skype (for video), and Together.js  (for screen sharing and pointing) can co-exist.    

*Adding together.js to KA lite is easy.

It has NOT been easy to ensure that the coach and the student are interacting on the same page when doing Practice Exercises.  (Exercise Randomization is the problem).*

I need some help with this. It is a potentially great socio-technical innovation  for connecting  kids coaches, and connecting communities-in-need with coaches and role models from neighboring communities.

Jon.Schull@RIT.edu

**Comment by benjaoming** [comment]
Sorry that nothing happened in this issue @jonschull - it's an interesting proposal! A new and much more well-designed open source project has been started by Learning Equality. It'll do the same things as KA Lite but adding much, much more.

You can read about it here: http://learningequality.org/kolibri

I'm closing this issue now because we're getting KA Lite set for a new and more stabilized future, supporting existing deployments, but keeping the amount of new features at a minimum.. or entirely community driven! :)
