### ISSUE TITLE
Feature request: online KA Lite

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#134]
Use cases:
- Schools: When online access is possible / preferred for some members of a group, and not available to others, but all must share the same KA platform (a la HTH).  Accessing online can be much more convenient for those who can do so (no need to install, no need to physically transport anything from home)
- Prisons: When someone starts learning on KA Lite offline, then is released with their data.  Online access would allow them to continue learning at a public library, for example.

This may be a blocking issue for HTH deployment.

Issues and suggested implementations:
- Streaming would be expensive; however, requests for videos could be redirected (302) to amazon aws?
- Online installation would have to sync multiple zones worth of data with the central server.

**Comment by rtibbles** [comment]
This is off our roadmap now. Won't fix.

**Comment by jamalex** [comment]
This one I think would be good to leave open as a Nice to Have, since I can imagine quite a few use cases. It will only be feasible to implement it once we've got better DB-specific URL namespacing (0.15?), so it's a ways off.

And actually, once we've got things to a more namespaced... space... this approach could actually make things *easier*. It means we don't have to have as much divergence between the central and distributed servers; the central server could consist of:
1. an entry portal
2. a place to manage organizations
3. a place to register DBs to organizations
4. some tools for aggregate reporting/data export across multiple DBs within an org
5. separately-mounted distributed server URL entry point for every DB, where you can engage with every feature that's in the distributed server (content, user administration, coach reports, etc), the exact same way you would if logged into the distributed server

I see quite a few advantages to this:
- We wouldn't need to deal with the headaches of making sure distributed server features integrate cleanly into the central server, since we would basically just be running the *same thing* on the Hub (could even have (5) launch in a new tab, with styling identical to distributed server)
- We wouldn't need to maintain as much parallel documentation for the central server, if most things were done exactly the same way as on the distributed server. Users (of all types) could also more easily transition between distributed and central server, with a familiar user interface and navigation.
- It should be easier to manage a unified permissions system this way.
- By default, you would need to know the DB UUID in order to get to the login page (thus helping to limit exposure). But we could have a central server org admin feature where you set up a nice readable URL slug alias that would redirect to the login page for that DB.

Some challenges (but things we'd probably need to deal with in some form anyway):
- What channels do these central server versions of the distributed server subscribe to? Maybe just all channels?? And more generally: How do we handle coach reports for usage data from a channel the current installation isn't subscribed to?

**Comment by mjptak** [comment]
Sounds like a great place for people to share/build community with things
like exercises (Perseus or otherwise)...think about it....Portuguese
exercises translated into English...not only the other way around.  Lots of
possibilities but having witnessed things like the Google/Trimble 3d
warehouse grow and flourish in the ecosystem of an even sort of open source
community I am hopeful.

**Comment by benjaoming** [comment]
Closing this issue so it doesn't advertise a false promise of a kind.

Of course, the initial motivation should be food for thought for the new Kolibri project: http://github.com/learningequality/kolibri
