### ISSUE TITLE
Watching a video does not update the UserLog stats.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite#2459]
**Branch** release-0.12.0

**Milestone** 0.13.0

**Current Behavior** As noticed on #2000 - `UserLog` stats are not updated when student is watching a video.   

**Expected Behavior** `UserLog` stats must be updated when watching a video.

**Possible Solution** The `UserLog.last_active_datetime` field is used to determine user stats.  So calling the `UserLog.update_user_activity()` will update that field and stats.

The fix may be anchored whenever points are given for watching a video.

Please note that stats are updated while doing an exercise (whenever the user submits an answer).

**Comment by djallado** [comment]
@aronasorman.

I verified this issue and I think this issue is already been fixed because I can't replicate it. 
Points on watching video is saved in VideoLog automatically.

**Screenshots are attached below:**

1. **Student account:**
![video_pt](https://cloud.githubusercontent.com/assets/8664071/6018635/2b4e789e-abd3-11e4-93cc-f5b0980c626d.png)

1. **VideoLog in admin account:**
![video_admin](https://cloud.githubusercontent.com/assets/8664071/6018645/4c175cf8-abd3-11e4-853e-b54d1879e97a.png)

The points are not the same in two screenshots because I capture in `Student account` first then `VideoLog in admin` without stopping the video. So obviously points in `VideoLog in admin` is higher.

**Comment by aronasorman** [comment]
Thanks @djallado!
