### ISSUE TITLE
Run the base test suite during kaserve.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite#2657]
**Branch**: `develop`

When `python manage.py kaserve` is run, it should run the base test suite from #2417 and show the test errors to the user.

Note: You can do `python manage.py test basetests` to run the base test suite manually.

**Comment by benjaoming** [comment]
I'm not sure if doing this as a part of testing is a good idea, seeing that testing.base uses TestCase and is modelled as real test cases. This can imply using test libraries, different settings (test settings may vary, although ideally they don't), temporary databases (or wrapping things in transactions), and a general idea that you can manipulate the system however you want, because it's run in a test environment. I really wouldn't recommend getting anything near that into a production system.

We test things so we know they work when we ship, but testing things after they're shipped, furthermore each and every time that a supposed-to-be-functioning and already shipped basic thing like `kalite start` is run would be a kind of contradiction to that principle.. also, it slows things down when `kalite start` is already way too slow.

But it would be fine to have some sanity checks during start up, and I think we should call it "diagnosing" rather than "testing".. but the idea of diagnosing touches on some other issues like better logging and exception handling.

Also, exactly what is it that we would like to know when people call in from the field and say "this doesn't work" ? Version, OS, install path, content dirs are writeable, text of possible exception in kaserve, ...?

**Comment by aronasorman** [comment]
Since we're now moving to individual installers I don't think this is needed anymore. Installers instead should verify that they have all the needed dependencies to run KA Lite in their respective platforms.

**Comment by benjaoming** [comment]
agreed!
