### ISSUE TITLE
Have a ka-lite binary to stop and start the server

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#2757]
So for Ubuntu we have `service kalite (stop|start)`, but it would be nice to have a standardized command line interface for controlling the server. Hence I propose the `kalite` binary, with the following commands:

`kalite start`
`kalite stop`
`kalite restart`
`kalite gui` (if supported by the platform)

Which should call out the right scripts found in the ka-lite/scripts/ directory. We can then modify the startup scripts to just simply call the right arguments.

**Comment by aronasorman** [comment]
Duplicate of https://github.com/learningequality/installers/issues/2

**Comment by benjaoming** [comment]
We have just discussed how to separate and encapsulate the kalite application vs. the kalite system service and come up with the following suggestion:

    $ kalite start       <- executable 'kalite' provided by main 'kalite' package
                \
               invokes
                  \
                 $ kalite-service start    <- provided by separate kalite-service-upstart
                    /        \
                 fail       invokes
                  /            \
             $ start.sh      $ service kalite start
          (this is run in        (this command
          case we fail to        is part of the
             find any             package which
          'kalite-service'        supplies
            in the PATH)         os-specific
                                   services)

**Comment by benjaoming** [comment]
If the UI should be able to know what's going on, we need something like a `kalite status` command, too.

**Comment by jamalex** [comment]
Yep! I'd been thinking a `status` command would be part of this. :+1:

**Comment by aronasorman** [comment]
A `status` command would also fit in well with the software update process, as a standard way of querying if the server is up, rather than assuming it's gonna be up in 10 seconds (what we do now with the update process).

**Comment by benjaoming** [comment]
First step is now being implemented in PR #2893

Now the next step will be for the PR to attempt calling a `kalite-service` command if such is available on the path. Potential problem: If we have several versions of kalite running on the same machine, calling whichever kalite-service is on the path is maybe not a good idea.

Rather than that, I'm contemplating taking `kalite-service` out of the equation such that it will be the init-scripts/services calling `kalite start` and not the other way around. This would match how soooo many other daemon applications are doing things already.

**Comment by cpauya** [comment]
Hi @benjaoming - we've have been using your `bin/kalite` executable on the [Mac OS X .app file issue](https://github.com/learningequality/installers/issues/3) and it's very useful.

May I ask if there are plans to include a command to run setup like `kalite setup`?  

This one will call `setup_mac.command` on OS X or `setup_windows.bat` on Windows or `setup_unix.sh` on Linux and I think it's important to be used by the installers also.

And this can also be used to "reset" the installation of KA Lite.

/cc: @aronasorman @jamalex

**Comment by jamalex** [comment]
If there's a `kalite setup` command, it shouldn't need to run the command/bat/sh scripts, since it's already in Python-land. Should be able to run the `setup` Django management command directly.

As I understand it from a previous conversation, `kalite manage setup` should work, if it's proxying through to manage.py with that.

**Comment by cpauya** [comment]
Thanks for verifying that @jamalex - will use `kalite manage setup` then.

**Comment by benjaoming** [comment]
I have one problem with `kalite manage setup`... it's based on a management command that's only called 'setup'... i don't like how generic that is... could easily conflict with another django app. It would be nice if we renamed it `kasetup` and proxied everything through `kalite setup`.

Another thing... the `kalite setup` part should only do cross platform setup stuff... the rest should be left for the installer. I'm not sure if it currently does platform specific stuff, but in case it does, I'll send you a request later..

Oh, and not to worry... I'm not deleting any of the current setup scripts... just trying for 0.13 to write alternatives for them.

**Comment by jamalex** [comment]
Sounds good. One caveat: we have a number of external places (e.g. Ansible scripts) that call the "setup" command directly, so I would opt towards not changing it. Since it's a command for the main app (not a pluggable app), I don't forsee name collisions. Also, we want to avoid calling too many things "ka-", since the app will soon be renamed and generalized.

**Comment by aronasorman** [comment]
Fixed in #2893
