### ISSUE TITLE
Redirect Loop Issue

### ISSUE THREAD

**Issue by kkmach** [learningequality/ka-lite#2872]
Trying to access video downloads page

http://127.0.0.1:8008/securesync/register/?next=%2Fupdate%2Fvideos%2F

More details:

```The webpage at http://127.0.0.1:8008/securesync/register/?next=%2Fupdate%2Fvideos%2F has resulted in too many redirects. Clearing your cookies for this site or allowing third-party cookies may fix the problem. If not, it is possibly a server configuration issue and not a problem with your computer. ```

**Comment by kkmach** [comment]
https://s3.amazonaws.com/uploads.hipchat.com/86198/1615667/xcvNvUwpK64kZ2w/data.sqlite

**Comment by MCGallaspy** [comment]
@kkmach Is this on the develop branch?

**Comment by kkmach** [comment]
no I think Jamie and I found it on the master or central master.

**Comment by MCGallaspy** [comment]
Managed to recreate this issue by judiciously deleting database rows in both the distributed server and the central server. Check out the file:
`/ka-lite-central/ka-lite-submodule/python-packages/securesync/devices/api_views.py`, starting around line 73.

If a device does not have an associated zone in the central server, instead of claiming the device has already been registered let's see if we can fix up the database.
