### ISSUE TITLE
Management command for exporting to ZIM format

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#2894]
The introduction to the [ZIM format](http://www.openzim.org/wiki/ZIM_file_format) says the following:

> The openZIM project proposes offline storage solutions for content coming from the Web.

A good way to learn about this format, would be to create dumps for it. The [Kiwix project](http://www.kiwix.org) already has this feature on the wish list.

I would seem like a big shortcut for the Kiwix project to have KA contents through KA Lite and a good way to start exchanging ideas and experience between the two projects.

The Kiwix project might have someone ready to work on this feature directly.

I'm envisioning the following pattern:

```
$ bin/kalite manage zimdump > khan_academy.zim
```

There should probably also be options for filtering, but for starters, It could just dump everything in the kalite installation, and customizing it would be the same as customizing the topics and videos in the installation.

**Comment by kelson42** [comment]
Thank you benjaoming for opening this ticket. Our position for now is that KLite is a great software, but we have a few use cases were it's not available (due to the client/server nature of the software). So, as a "cheap workaround" it might be interesting at least to propose the videos in a ZIM container.

To do that, we need:
1 - A scraper (from KA)
2 - A solution to put all the video in a nice set of HTML pages
3 - Create the ZIM file

It looks like KLite does more or less 1&2 already, so we will would like to improve/reuse that part. We don't have a timeline for now (and no resources), but if you are agree or confirm this approach, I'll put this task in our pipe.

**Comment by rtibbles** [comment]
For a non-client/server mode of interaction with the videos Khan on a Stick has the static HTML files generated: http://mujica.org/khan/ this might be a quicker way of getting KA into a ZIM format.

**Comment by benjaoming** [comment]
This is being worked on in another project: https://github.com/openzim/kalite
