### ISSUE TITLE
Sidebar scrollbar issues

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#2923]
I find that it's hard to know that there's more content *below the folds* when the scrollbar is relatively invisible. Imagine a tablet that's used by a kid sitting in broad daylight.... wearing sun glasses and drinking tequila :)

Example:

![scrollbar](https://cloud.githubusercontent.com/assets/374612/5984031/3ae2fe28-a887-11e4-9b7a-2cd295998a94.png)

**Comment by 66eli77** [comment]
lack user feedback

**Comment by benjaoming** [comment]
@66eli77 what kind of feedback would you like?

**Comment by 66eli77** [comment]
@benjaoming I see the problem of making the scrollbar subtle, but such design also make the already heavy sidebar nav system look more unified and clean. We want to find the balance in between. That's why more user feedback can help us find the balance. The South Sudan Teacher training program are among the first group to use the new sidebar nav system, they may give us more feedback on this in the near future.

**Comment by benjaoming** [comment]
@66eli77 okay but since the scrollbar only shows up when it's needed and essential, it could just be styled in a solid colour that's more visible? Like increasing opacity to 90% ?

**Comment by 66eli77** [comment]
@benjaoming Totally, we can iterate the design on that.
