### ISSUE TITLE
Multiple "Manage" tabs

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#2990]
On branch `develop`, logged in as a coach, I find multiple "Manage" tabs on many different pages (emphasis mine):
![ss](https://cloud.githubusercontent.com/assets/8888020/6117861/ac4190d8-b06c-11e4-8be6-69bfa67293eb.png)

**Comment by jtamiace** [comment]
adding onto this, there's no way to log out: 

![teach nav](https://cloud.githubusercontent.com/assets/6668144/6118092/cd58b6c8-b06e-11e4-8beb-efda96b178ee.PNG)

**Comment by benjaoming** [comment]
@jtamiace that looks like an error with floating, does it disappear if you make the screen size bigger?

**Comment by cpauya** [comment]
Hi @MCGallaspy 

We include the `base_teach.html` and `base_manage.html` templates in many templates like `distributed/homepage.html` and `distributed/learn.html` and these included files set the `active` css class inside their respective blocks (ie: `block teach_active_admins`).

The duplicate happens inside the `distributed/base.html` wherein those blocks are both set to `active`.

I think someone else more familiar with how these navigation links must be set should work on this and #2997 as we might end up introducing more bugs instead of fixing them.

/cc: @jamalex @aronasorman
