### ISSUE TITLE
Burn down get_all_import_child_modules

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3042]
This function right here imports everything under a module. This is nice for convenience, but it's annoying as hell when writing tests and you don't want to import an entire module.

I also think that it's more idiomatic python to explicitly import the modules we need, and not hide it under an automatigical import statement.

**Comment by cpauya** [comment]
Yes please! :+1: 

1. It's on the Zen of Python / `import this` - `Explicit is better than implicit.`.
2. Loads unused module for tests or other modules.
3. It's breaking our IDE`s ability to check for import issues (unused imports, PEP-8, etc).

**Comment by MCGallaspy** [comment]
One specific issue I've been encountering with `import_all_child_modules` is with `fle_utils.handlebars`... since every file from the module is loaded, it ends up happening (through more than one invocation of `import_all_child_modules`!) that a bunch of very slow functions from `topic_tools` are called. This is almost certainly not intended, as the first offending instance of `import_all_child_modules` is called by a statement that's just trying to get the directories of all `settings.INSTALLED_APPS`.

**Comment by MCGallaspy** [comment]
So whatever time is ostensibly saved elsewhere by not having to specifically import your favorite functions from `fle_utils.handlebars` is almost certainly lost (and more) when these nasty slow `topic_tools` functions are called. A first step to addressing this issue could be to track down imports of `fle_utils.handlebars` and make them specific, i.e. change it to `from fle_utils.handlebars import x`, where `x` will have to be determined on a case by case basis.

Indeed, a more general outline for getting rid of this stinker would be to find all modules that use it, subsequently find where *those* modules are imported, and change the imports as I've described. Is my understanding of this issue correct? @aronasorman @benjaoming 

Perhaps we can make this an intern project? :P

**Comment by MCGallaspy** [comment]
The `testing` module is also an offender.

**Comment by rtibbles** [comment]
Partially addressed this in #3157 - but didn't want to get into all the test modules that use this just yet.

**Comment by benjaoming** [comment]
YES PLEASE!! It breaks my IDE, gives me circular imports, unused imports and a generals feeling of just "WHAT!!".

The other day at Luwinga Secondary, I found (in a school, without internet, lots of other priorities) that a WSGI application was breaking because of circular imports in the testing.... yes in testing!? And the mod_wsgi application had been running fine on another machine, which leads me to believe that some of the problems encountered aren't all that deterministic. So I'd have to say this has already cost me too many efforts, and I'll be dancing on this function's grave.

**Comment by rtibbles** [comment]
This is now completely fixed in #3157.
