### ISSUE TITLE
Coach Reports: incorrect error displayed, date issues

### ISSUE THREAD

**Issue by tk21** [learningequality/ka-lite#3047]
Branch: develop

Expected Behavior: There should be no error message. When clicking on "scatter report" and "timeline report", display learner's progress.

Current Behavior: Error message given : "No learner accounts in this group have been created". Data can only be displayed if starting-time and ending-time are extended way into the past or way into the future (even though there is indeed data in the specific date-range given). 

Steps to reproduce:

1. Log in as the coach
2. Go to reports
3. Try to click on "Scatter Report" or "Timeline Report"
4. Nothing will display, sadness.

**Comment by jesumer** [comment]
Hi,

I have an initial fix on this issue but I think it's not a good idea. I found it hard to fix since It is a rocket science which we will consider the validation of the Coach groups, learners and their finish exercises. I need some help here since I am not familiar about how the codes happening in coach report. Here's my screenshot of my quick fix:
![screen shot 2015-02-20 at 5 56 29 pm](https://cloud.githubusercontent.com/assets/2810009/6284338/f4fb2832-b929-11e4-810a-eae13cdee868.png)

**Comment by cpauya** [comment]
@jesumer Let's refactor this to work as a proper form.  You don't have to worry how the filters work on the back-end because I think they already work as intended, it's the front-end form behavior that is confusing (that `Go` button and the resulting error message).

Suggested form behavior:

1. When a report type is selected, show it's corresponding filters like the date range boxes.
1. When `Go` button is selected, validate the filter values.
1. If form values are valid, submit the form request.
1. On page load, we show the report or equivalent error message like "No learner accounts...".

This is a quick work-around for the fix as mentioned by @MCGallaspy at #3054.

**Comment by jesumer** [comment]
Hi @aronasorman,

 @cpauya. Yes I agree about this. 
This issue is related to this [issue](https://github.com/learningequality/ka-lite/issues/3051)

**Comment by MCGallaspy** [comment]
Coach reports no longer exists in this form.
