### ISSUE TITLE
No Python videos in 0.13.x

### ISSUE THREAD

**Issue by DragoonHP** [learningequality/ka-lite#3083]
Just updated to 0.13. I love the new interface but I noticed that the Python section is not there. Any reason why it was dropped?

**Comment by jamalex** [comment]
Hey @DragoonHP! Thanks for checkout out the 0.13 prerelease.

Looks like KA may have removed the Python lessons (perhaps to avoid confusion with their JS-focused CS curriculum?). Do you see them on KA's site anymore? If you can find them on there, we can look at why they're not being included, otherwise there's probably not much we can do.

**Comment by DragoonHP** [comment]
Just checked KA, and they seems to have removed python for good.

So will we have to delete the python videos manually, or is there a script/command to do that?

**Comment by mjptak** [comment]
What....KA lite build with Django and Python but with no Python videos and exercises?   Luckily "channels" are built into this functionality and there is no shortage of outstanding Python series out there (I loved David Evans' course at Udacity)  The beauty of Version 0.13...the possibilities of version 0.14.

**Comment by MCGallaspy** [comment]
@DragoonHP if you want to get rid of the video files, you'll probably have to delete them manually. But it shouldn't affect your installation to just keep them (except that they'll take up storage space, of course). @jamalex wanna chime in?
