### ISSUE TITLE
For exercises, should we allow user input while the keypad is open too?

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#3100]
I understand that when the keypad is open, users should be using it instead of inputting from their own keyboard, but it took me a while to figure out that I had to close it before I could input. 

Might be because I see using the keypad as optional on a desktop computer but I can see why this would be a useful restriction for users that are doing exercises on tablets.

![keypad](https://cloud.githubusercontent.com/assets/6668144/6339552/d139fb0a-bb6b-11e4-8413-b807f50296ad.PNG)

**Comment by rtibbles** [comment]
Problems I can see with solving this:
* we need to disable the input box when the keypad is open in order to prevent system keyboard popping up on Android.
* The reason we have the 'Show keypad' option is because there is no completely reliable way of checking that you are using a touch screen device, so if someone is on a tablet it has not been shown by default and someone toggles it on, then they will may now get the system keyboard popping up when they try to answer.

The latter may not be an issue as pressing 'show keypad' may defocus the input box, but it does make it harder.

Also, why does it look so ugly?!

**Comment by rtibbles** [comment]
Won't fix.
