### ISSUE TITLE
Direct link for videos

### ISSUE THREAD

**Issue by rayeshman** [learningequality/ka-lite#3137]
Hi,
I live in Iran and Internet's expensive and slow here so I can't download videos myself, and I should download them at my university.
And my university won't allow me to run ka-lite to download video files, BitTorrent Sync is unavailable because of sanctions against my country and YouTube is blocked by the government so there's only one way left for me to download video files and that's using direct links.
Would you add an option for listing the direct links of videos or just make a text file of direct links so I can download them in the university?

Thanks a lot.

**Comment by MCGallaspy** [comment]
Hi @rayeshman, I'm not aware of a direct link for the videos. Perhaps someone else can weigh in? @jamalex

**Comment by jamalex** [comment]
(Below is all for version 0.13, i.e. the develop branch, to be released
soon)

To get a list, you can run (from the `ka-lite/kalite` directory) `python
manage.py shell_plus`, and then type in the following (pasting may work, if
you have IPython installed):

```
from kalite.topic_tools import get_content_cache
for video in get_content_cache().values():
    url = video["download_urls"].get("mp4")
    if url:
        print url.replace("http://fastly.kastatic.org/", "
http://s3.amazonaws.com/")
```

(remove the .replace part if it turns out to be easier to download through
fastly instead)

**Comment by jamalex** [comment]
Here's a list, for convenience:
http://staging.learningequality.org/media/video-file-list.txt
