### ISSUE TITLE
enable optimization option on RPi installation

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#3272]

**Comment by benjaoming** [comment]
Hey @66eli77 or @aronasorman there are some issues with this PR:

1. It's going the wrong way: We're cluttering a new interface because of legacy code
1. It adds an *undocumented* option to something that we worked hard on making documented and which we discussed and carefully selected the functionality of.
1. The undocumented option calls some more undocumented/uncommented functions
1. PEP8
1. Why do we even have a CLI for making a quirk for "RPi" (I suppose you mean Raspberry Pi) ?
1. The `package_selected()` function in kalite.settings is a utility function that looks at some weird CONFIG_PACKAGE var, which I don't understand half of, except for the following:
  1. It looks in local_settings for CONFIG_PACKAGE
  1. If it doesn't find it, it uses platform.uname
  1. It may be None <- but what does that mean!?
  1. See #3388

Since setup_unix.py is being obsoleted, I suggest that we revert the bash installer to using it's own uname parsing and not adding extra quirks to what's supposed to be a more clean codebase.

@66eli77 when you're writing changes to a file that has ~33% comments, you should be adding comments to at least the same amount ;)

**Comment by 66eli77** [comment]
@benjaoming  I agree on your approach, no need to run a circle to get the RPi hardware info.
