### ISSUE TITLE
More logging calls

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3327]
We need a ton more logging if we wanna stand a chance debugging installations far away.

Proposal:
1. Create a set of rules of when to use the current logging levels (DEBUG, INFO, WARNING, ERROR).
2. Create a new logging level, VERBOSE. The idea here is to be able to know the code path taken by just looking at VERBOSE logs.

**Comment by benjaoming** [comment]
Not sure why I didn't open up an issue about this before because it's been mentioned lots of times.

1. We need consistent logging, should be inspired by the [logging cookbook](https://docs.python.org/dev/howto/logging-cookbook.html#logging-cookbook) such that we have a parent `kalite` logger and all other loggers use `__name__` such that they attach to the parent logger's configuration.
1. We should use settings.LOGGERS in django to control all logging.
1. Output to files as well and use rotation, as described in [Using file rotation](https://docs.python.org/dev/howto/logging-cookbook.html#using-file-rotation).

**Comment by benjaoming** [comment]
Logging will get better now that it's centrally customized with `settings.LOGGING`. However, we should stop using settings.LOG and instead do:

```python
import logging
logger = logging.getLogger(__name__)
```

**Comment by benjaoming** [comment]
I've started implementing the above pattern `logger = logging.getLogger(__name__)`. We also have better logging handling through `settings.LOGGERS`.

And finally, we log to `~/.kalite/server.log`- which also works on Windows now.

I think it's reasonable to close this now - seeing that it's more of a task for future devs to slowly adapt the remaining codebase to proper standards.
