### ISSUE TITLE
Make Python sources PEP-8 compatible.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite#3344]
Branch **develop**
Target **before 0.14.x**
Expected:  Compatibility with [PEP-8](https://www.python.org/dev/peps/pep-0008/).
Current:  We have a lot of PEP-8 violations on our Python codebase, so it would be good to finally address that.  Do not include those under the `python-packages` folder.
Possible Solution/s:  Address these issues:

1. Make the Python codes be PEP-8 compatible (except for the max chars per line).
1. Set the [maximum line length](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) from 79 to 129 as initially discussed with @aronasorman.
1. Exclude codes under the `python-packages` folder.

**Comment by aronasorman** [comment]
The best time to get this in is right before 0.14 dev starts, or after the feature dev is finished.

**Comment by aronasorman** [comment]
Will work on this.

**Comment by benjaoming** [comment]
This won't be done unless we manage to merge/close all existing PRs. Which will take a while. I'm able to do this quite quickly with automated tools, and would happily do so, but I don't really think we should maintain an issue for it since it might trigger someone to do a giant PR that we won't be able to merge.
