### ISSUE TITLE
Register device link redirect to page not found.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#3544]
Branch: `Develop`
Expected behavior: `register device link` must not redirect to page not found.
Current behavior: `register device link` redirect to page not found
Steps to reproduce: log in as coach and click the `register device link`.

![ka-lite-a](https://cloud.githubusercontent.com/assets/8663934/7291451/49b96194-e9c3-11e4-9677-cba514877c87.gif)

**Comment by MCGallaspy** [comment]
@rtibbles the issue here appears to be that a user without sufficient permissions is redirected based on the setting (in the distributed app) `LOGIN_URL`, which is no longer a valid url -- hence the 404. We should probably change the way permissions like this are handled. Is there a GET parameter which will cause the login modal to be displayed?

**Comment by rtibbles** [comment]
There will be once #3729 is merged (I believe I had changed LOGIN_URL to this at some point to, but that seems to have got lost in translation at some point).

**Comment by MCGallaspy** [comment]
Cool, do you expect that PR to resolve this issue then?

**Comment by rtibbles** [comment]
No. But I can update it to change the LOGIN_URL, as that seems the best approach.

**Comment by rtibbles** [comment]
Will fix up shortly.

**Comment by MCGallaspy** [comment]
Agreed, then I think this will be fixed by #3729.

**Comment by rtibbles** [comment]
Fixed by #3729
