### ISSUE TITLE
Move version.py version metadata to YAML

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3562]
I've had a couple of stupid commits before amending my mistakes when editing this file directly. If only there was a more human-friendly version of JSON, meant for humans to use...

Oh cool there is one: http://yaml.org/spec/

So my suggestion for here is to create a new pre-commit hook that will convert the yaml file to JSON before committing. That JSON file will be the one that's read by `version.py` on app startup.

**Comment by aronasorman** [comment]
@ruimalheiro wanna take this on? This should be pretty simple.

**Comment by jamalex** [comment]
> convert the yaml file to JSON before committing

I would recommend just having the conversion to JSON (which is just for efficiency, I'm assuming) happen during the build process, since:
- we can't rely on everyone having these precommit hooks
- we can just have version.py load the YAML directly during development

It could look for the JSON file, and fall back to the YAML if the JSON didn't exist (might be good as a general-purpose function, as well -- `load_json_or_yaml`?)

**Comment by aronasorman** [comment]
@jamalex sounds good.

**Comment by benjaoming** [comment]
Isn't the problem that we _aren't_ putting things in kalite.version and isn't that actually more a problem about not doing things conventional and accessible enough for devs?

I would suggest maintaining a CHANGELOG.md for conventionality. If we desire to show it to users, either dynamically render it to HTML with python-markdown (but don't think it's available) or automatically build an HTML version every time we change CHANGELOG.md

The change log IMO is mainly for people who are really interested in following the development... hiding it somewhere in the UI and in an unconventional python module or YAML file won't get us where we should be. The rest of the audience will read it on the blog or in a newsletter.

**Comment by jamalex** [comment]
> The change log IMO is mainly for people who are really interested in following the development... hiding it somewhere in the UI and in an unconventional python module or YAML file won't get us where we should be

In the web-based update process, we've experimented with displaying the incoming changes to the admin, so they can choose whether to update, and know what they'll be getting. So, a machine-readable format is useful for things like that. But the idea is just to have very high-level items in there, not a full changelog.

**Comment by benjaoming** [comment]
I'm not sure I understand correctly? If you're running a local 0.13, it won't have the YAML / kalite.version of 0.14 so you can only display the changes after upgrading? Or you mean that people should see them by calling an external online webservice?

**Comment by ruimalheiro** [comment]
@aronasorman I will take a look on this! :+1:

@jamalex and @benjaoming thanks for the insights!

**Comment by benjaoming** [comment]
@aronasorman please see my comments in #3602 before closing this?

**Comment by MCGallaspy** [comment]
Done, and management command exists for use by package builders to turn yml files into json.

**Comment by benjaoming** [comment]
@MCGallaspy, I would think that the compiling is the responsibility of the repo owner, same as with compiling language files, javascript compressing etc... so whatever you do as a packager, you can always just grab a snapshot of the source and distribute that without worrying about building KA Lite's internal logics.

**Comment by aronasorman** [comment]
@benjaoming it might be good to encapsulate all the special KA Lite logic into a Makefile. That way packagers everywhere will have a single recognized entrypoint to building KA Lite for distribution.

**Comment by benjaoming** [comment]
@aronasorman that could be a good idea, but non of this is being compiled for a specific system, so I still think it would be okay to leave this for source repo owners... even the non-packaged source code needs it.

**Comment by aronasorman** [comment]
@benjaoming by source repo owners, do you mean us, the developers of KA Lite? So you're saying we should commit the compressed JS files, jsonified yml files, and other things we will generate in a built process, into the repo? Sounds counterintuitive to me, and defeats the whole purpose of having a build process in the first place.

**Comment by benjaoming** [comment]
@aronasorman yes that's what I'm saying :) When you change a .yml file, you should run `compileymltojson` and commit the .json file, too. This is the same procedure for .po and .mo. Otherwise you force anyone who wants to use the source to know these commands and run them. Python projects are normally run-able without building anything.

**Comment by jamalex** [comment]
The load_yml_or_json function we've discussed a number of times means you
don't need to build anything when running from source.

**Comment by benjaoming** [comment]
@jamalex you need pyyaml for building "on the fly".

But I don't see the problem in what I'm saying. Why should it be packagers responsibility when the repo owner needs to ship a one-size-fits all json? :)

**Comment by aronasorman** [comment]
@benjaoming but we don't recommend anyone from using the bare source for production usage anymore. I think package builders should be smart enough to read documentation on how to make KA Lite usable in production (running `collectstatic, compileymltojson, bundleassets` etc.) or if they see something like a `Makefile` then it should be easy for them to read what's in there.

If this is more of an issue on how to get `pip install` running seamless, then there might be ways around that, rather than bloating the repo even more.

**Comment by benjaoming** [comment]
`collectstatic`: Is not run by packagers
`bundleassets`: Might be run by packagers, but should certainly never be included in the source
`compileymltojson`: Would create a JSON file usable for all

If you create a make file, what would you put in it, except for `compileymltojson` and maybe `compilemessages`?

Conceptually, I'd say this:

Repository owners and source code distribution: Handles a bare-bones KA Lite where "setup.py install" or "bin/kalite" will render running versions of KA Lite, not including data fetched from online sources. This should contain a source that's universal to all systems.

Packagers use the repository sources and prepares automatic processes that can deploy them on user's systems. If they need to change the sources, they are essentially patching them, a pitiful task that's always carefully tracked and annoying to anyone packaging because they risk not being able to apply upstream cleanly. By requiring packagers to execute django management commands, you are asking them to have a build environment that uses the application itself and some specific configuration for the application. However, build environments might not really know anything about the application. I know that in this case it might seem harmless, but what I mean is to draw a line between what we maintain in the repo and what packagers are responsible for... I don't see why they should all create the same JSON results, same reason as why packagers don't normally compile .po files.

**Comment by jamalex** [comment]
> If you create a make file, what would you put in it, except for compileymltojson and maybe compilemessages?

There are going to be a large number of steps in the build process, which will be required in order to create an efficient bundle usable for deployments. This includes JS minification, JS concatenation, Handlebars template pre-compiling, LESS compiling, and much more. These will require the presence of node.js among other tools (no way around it, for compiling Handlebars/LESS), so we can't expect `setup.py install` to create a full distributable build, without some advance preparation stages.

> @jamalex you need pyyaml for building "on the fly".

Right, so that would be in requirements_dev.txt

**Comment by benjaoming** [comment]
But these are all steps that I propose should be handled within the repo and *not* by packagers, because they are universal to ALL distributions, just as with the .po and .mo files. Hence my previous attempt to discern between source repository and packaging.

So if you change a .js file, you should also commit the minified version of that .js file. This is even done in .js distributions on github.. look at bootstrap. I would say that the argument for this is: Since it's not a system-targeted build but rather a universal build, it goes in the repo. [An example.](https://github.com/twbs/bootstrap/tree/master/dist)

My take on this would be: Do the Make file or some other build script. But let it be the responsibility of the repository owner and not the packagers.

**Comment by jamalex** [comment]
> So if you change a .js file, you should also commit the minified version of that .js file

Hmm, wouldn't this lead to merge conflicts *every time* two users change any lines in a JS file? It also very quickly bloats the repo. I thought this was the point of "source" vs "built" modes.

**Comment by benjaoming** [comment]
> So if you change a .js file, you should also commit the minified version of that .js file
>
> > Hmm, wouldn't this lead to merge conflicts *every time* two users change any lines in a JS file? It also very quickly bloats the repo. I thought this was the point of "source" vs "built" modes.

It only "bloats" the repo with files that are useful to everyone. Hence the example with .mo and .po files. You won't get conflicts in a minified file more than in a JS source AFAIK, but otherwise the conflict is pretty easy to solve.

**Comment by jamalex** [comment]
> You won't get conflicts in a minified file more than in a JS source AFAIK, but otherwise the conflict is pretty easy to solve.

Minification puts everything into one line, so yes, conflicts will be much more frequent. Especially as the build process is going to be bundling many JS files into a single file, so we would have a merge conflict anytime anybody changed anything in any one of those files in parallel. And it then means manually resolving those conflicts before PRs can be merged, which may be "easy", but is a huge hassle.

Also, we've done something similar in the past with CSS and LESS, and people ended up making changes to the CSS which then got overwritten.

It would be good to have a sync up about the process @rtibbles and I have been planning for building frontend code (with browserify).

> This is the same procedure for .po and .mo.

Mo files get into KA Lite through the "language pack" system, and hence shouldn't be bundled into the codebase anyway (in our case).

**Comment by benjaoming** [comment]
@jamalex 

> Mo files get into KA Lite through the "language pack" system, and hence shouldn't be bundled into the codebase anyway (in our case).

But that's standard practice (even though kalite has separate language packs containing application language). Maintaining .mo is very pain free because the .mo files are marked as binaries. You can do the same for a .min.js, forcing the git repo to understand it as a binary [1].

> Also, we've done something similar in the past with CSS and LESS, and people ended up making changes to the CSS which then got overwritten.

I don't think people will make changes to .min.js or .min.css unless they are very patient :)

> Minification puts everything into one line, so yes, conflicts will be much more frequent. Especially as the build process is going to be bundling many JS files into a single file, so we would have a merge conflict anytime anybody changed anything in any one of those files in parallel.

*If* you have a conflict because of minification only, then you know that the *source* is correct and you can just rebuild it and use "git checkout --ours". You can even automate this merging strategy [1].

But that's only if you have a conflict.

Btw.. here are some small fixes for the issues introduced from built files:
[1] http://blog.andrewray.me/dealing-with-compiled-files-in-git/
