### ISSUE TITLE
Incorrect information in learner-facing user manual

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3665]
The documentation section for learners on [how to use the exercises](https://learningequality.org/docs/usermanual/userman_learner.html#how-to-practice-exercises) is not very fleshed out (it could use some screenshots), and also contains inaccuracies (describing how things worked in 0.12):

> The bar on the top right will display your progress as you go through the exercises. After 10 correct answers in a row, your points for the exercise will be added to our total and you will have mastered the exercise. If you get an answer wrong or ask for a hint, all the points you have earned for this exercise will be lost.

In 0.13, you only need to get 8 out of the last 10, and you never suddenly lose all your points for an exercise. See the blog post: https://learningequality.org/blog/2015/ka-lite-013-released/

**Comment by MCGallaspy** [comment]
> and you never suddenly lose all your points for an exercise

This contradicts my experience -- using a hint or getting the incorrect answer means you don't accumulate points for a question, but points are not lost from previous correct answers. Is that what you mean @jamalex ?

**Comment by MCGallaspy** [comment]
Exercise screenshots are a tricky business, since it's not a given which exercises will appear on the server building the docs. Right now we can ensure assessment items are on the field server by provisioning with ansible. If someone attempts to build the docs without the appropriate exercises downloaded, it may fail ungracefully.
