### ISSUE TITLE
Uncaught error on Learn page

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3743]
On `develop`:
Observed behavior:
Occasionally (I haven't been able to reproduce this reliably yet :( ) I see the following error in a red bubble on the learn (`/learn/khan/`) page:
>Unexpected error: 'str' object has no attribute 'get'

Steps to reproduce:
Unknown at this time. Please report if you encounter this error, too!

**Comment by MCGallaspy** [comment]
Logged in as a student, I got the following bubble alert on `/learn/khan/`:

> This content was not found! Please contact your coach or an admin to have it downloaded.

Could it be related? This message probably shouldn't appear on this page.

**Comment by rtibbles** [comment]
If this is still extant, this is because when accessing a node from the 'child' attribute of the topic tree, this now just returns the id for that node, rather than the node itself. So, things try to do a .get on the str of the id, not on the node itself.

I am fairly sure that I have cleared up all instances of this, but would be interested to know if anything else crops up.

**Comment by MCGallaspy** [comment]
We'll see if this pops up again.

**Comment by MCGallaspy** [comment]
I've been noticing a pattern. Seems as though if one of the caches has been invalidated and is being rebuilt (such as the content cache when you download a language pack), then it's possible to get errors like this when an API endpoint makes a request. Not yet confirmed.

**Comment by radinamatic** [comment]
I've been noticing this since yesterday on develop.

When I press the Learn button as a non-logged-in user, I get an empty sidebar and  the `Unexpected error: 'str' object has no attribute 'get'` error:

![str_object_no_attribute_notloggedin](https://cloud.githubusercontent.com/assets/1457929/8262008/5c691648-16cf-11e5-80ad-1b9599c18790.png)

When I log-in as Learner, that error message stays on and the welcome one appears:

![str_object_no_attribute_loggedin](https://cloud.githubusercontent.com/assets/1457929/8262029/92b87db0-16cf-11e5-8e7f-84277759ee81.png)

Sidebar is not empty anymore and I can choose exercises & videos fine... When I log-out, the above error appears just for a sec and than disappears.

When I log-in as Admin, I always get a glimpse of "Could not connect to server..." error for a sec before the Manage tab loads fully, as well as when logging out. Not sure if that's connected, though...

**Comment by MCGallaspy** [comment]
Probably fixed by #3906.

**Comment by radinamatic** [comment]
Ok, waiting for merge to test... 

On today's develop I noticed no errors, but it takes a couple of seconds for sidebar to populate, so it does seem empty for too long. Would it be possible to implement some kind of loading spinner inside?

**Comment by rtibbles** [comment]
Reports for that issue here, @radinamatic #3835 

Spinner is coming in 0.15.
