### ISSUE TITLE
Create a single and consistent setting for the listen port

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3749]
branch: develop

Despite KA Lite listening on another port:
```
kalite start port=9000
```

Our helpful message still prints port 8008:

```

To access KA Lite from another connected computer, try the following address(es):
	http://192.168.2.128:8008/
	http://127.0.0.1:8008/
[494587 refs]
[52263 refs]
```

**Comment by benjaoming** [comment]
That's not actually a valid command line option. Currently, LISTEN_PORT is hard-coded in kalitectl because of an inconsistency in how a "settings" variable exists, and that doesn't actually make sense then to try to set the variable outside of the environment.

If you want, we could change the issue to say "Create a single and consisten setting for the listen port" :)

**Comment by benjaoming** [comment]
In settings, RPi is using a default PRODUCTION_PORT 7007 and PROXY_PORT 8008, others have PRODUCTION_PORT set to 8008.

Now, the issue is that we want an option that sets the port from command line.

I'd suggest:

Port set as command line option '--port' => Environment variable KALITE_PORT set to command line option or 8008 default => Settings always use environment variable, because the port has to be known outside of the django.conf

As for the RPi default 7007 port, that would unfortunately have to be a logic that's dealt with in kalitectl which is unfortunate. Not sure why it has 7007 and 8008 as a proxy port or what that even means.

**Comment by benjaoming** [comment]
But so setting the port is a release blocker, right? The thing is that I find it difficult to have a consistent port setting that's based on local_settings.py or PRODUCTION_PORT

**Comment by MCGallaspy** [comment]
I'll have to take a look at this to decide what's viable.

**Comment by MCGallaspy** [comment]
The `port=9000` arguments doesn't seem to work for me at all -- server is not listening on whatever argument I pass.

**Comment by aronasorman** [comment]
@MCGallaspy I believe that syntax only works when DEBUG=False, because cherry py has a different flag syntax vs. the debug server. Maybe that's the problem?

**Comment by MCGallaspy** [comment]
Well that's silly, why don't we have consistent syntax?

**Comment by MCGallaspy** [comment]
It seems anyway that cherrypy vs. debug server is dependent on the `production` option, which is set by `kalite start` anyway -- so `kalite start` should always run the cherrypy server regardless of one's DEBUG setting.

**Comment by MCGallaspy** [comment]
@benjaoming is right, ports are kind of a mess. There's a CHERRYPY_PORT, PRODUCTION_PORT and PROXY_PORT. My plan here is to create one port setting and remove references to all the others, let it be set by an environment variable as discussed, and to accept a command line `--port` option.

**Comment by benjaoming** [comment]
Agree with @MCGallaspy that cherrypy should always run, regardless of `DEBUG`.. it's faster and we also want to test it as much as possible.

Also agree on adding `--port`, regardless that normal django syntax is this:

`python manage.py runserver 1.2.3.4:5678`

I think it's messy to parse and inflexible because it deviates from how normal options are passed.. so I would prefer that we do `kalite start --port=1234` and optionally at a later point in time, we can add `kalite start --port=1234 --address=1.2.3.4`..

If user runs `kalite manage runserver`, they get the Django HTTP server, and that's all good, and we should support that as well... but running that comes with Django's own setting for address and port that will ignore any other KA Lite address/port settings... and that's also just fine, since no one would want to mix up production port settings and the debug server port. So nothing to change in this regard!

**Comment by MCGallaspy** [comment]
> Agree with @MCGallaspy that cherrypy should always run, regardless of DEBUG.. it's faster and we also want to test it as much as possible.

I wasn't suggesting that, but I think it's a good idea. That said, cherrypy doesn't have the nice debug output of the development server.

**Comment by benjaoming** [comment]
I added a missing 't' in "consistent"... for consistency :)
