### ISSUE TITLE
Support for Apache with 0.13 (or 0.14, at least)?

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3802]
We ostensibly support running the KA Lite WSGI app via Apache. Some issues described here: 
https://forums.learningequality.org/t/installing-ka-lite-on-apache-as-virtual-host/227

Any ideas, @benjaoming? I believe you've done some Apache deployments of KA Lite recently?

**Comment by benjaoming** [comment]
1. Write permissions to the folder containing the SQLite file is a well-known behavior
1. I'm not sure what this is. Could be because the webserver's WSGI thread is killed because of a timeout? Maybe it is creating content caching for a first-run?

It would be recommended to run "kalite start" before deploying the server to check that all caches have been preloaded and things are working as expected. Then after that, set the permissions for database and content folders.

**Comment by benjaoming** [comment]
For reference, here's the Apache virtualhost we use in FAIR:

https://github.com/fairdk/fair-ubuntu-centre/blob/fe7e2efa670afd0d204a985f5fc4c381fde64ea5/installscripts/data/etc.apache2.sites-available.kalite.conf

I don't think there's much use in keeping this issue open as there's currently nothing indicating that there are issues. I have a running instance of the latest KA Lite development branch on Apache + mod_wsgi and it's working great :)
