### ISSUE TITLE
Assessment items as application data

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3898]
Currently the settings path for assessment items is hard-coded to be in the content root, which is a user data directory.

However, since this should be a shared piece of application data AND a download-able piece of user data, we need a condition that checks if the installation already provides bundled-in application data in a system-wide directory, `kalite.ROOT_DATA_PATH`.

Relevant code from `kalite.settings.base`:

```
KHAN_CONTENT_PATH = os.path.join(CONTENT_ROOT, "khan")
ASSESSMENT_ITEM_DATABASE_PATH = os.path.join(KHAN_CONTENT_PATH, 'assessmentitems.sqlite')
ASSESSMENT_ITEM_VERSION_PATH = os.path.join(KHAN_CONTENT_PATH, 'assessmentitems.version')
ASSESSMENT_ITEM_JSON_PATH = os.path.join(USER_DATA_ROOT, "data", "khan", "assessmentitems.json")
```

My proposal would be something like:

```python
_system_wide_assessment_items = os.path.join(ROOT_DATA_PATH, 'assessment_items')

if os.path.exists(_system_wide_assessment_items):
    ASSESSMENT_ITEM_ROOT = _system_wide_assessment_items
else:
    ASSESSMENT_ITEM_ROOT = KHAN_CONTENT_PATH

ASSESSMENT_ITEM_DATABASE_PATH = os.path.join(ASSESSMENT_ITEM_ROOT, 'assessmentitems.sqlite')
ASSESSMENT_ITEM_VERSION_PATH = os.path.join(ASSESSMENT_ITEM_ROOT, 'assessmentitems.version')
ASSESSMENT_ITEM_JSON_PATH = os.path.join(ASSESSMENT_ITEM_ROOT, "assessmentitems.json")
```

I'll have a look at this and figure out a way that does not affect old locations of assessment items.

**Comment by benjaoming** [comment]
@jamalex would you care to share some insights on this? I think it's very closely related to our discussion on how to distribute for .deb vs. NOT distributing updates that have assessment items and still being able to run on a multi-user system :)

**Comment by MCGallaspy** [comment]
Oh, looks like you have an open PR for this.

**Comment by MCGallaspy** [comment]
Is this addressed in #3809?

**Comment by benjaoming** [comment]
@MCGallaspy no, this is a PR on top of #3809 in order to keep it shorter.. but the other PR is a dependency :)

**Comment by MCGallaspy** [comment]
Okay, bear with me, I require thorough explanations because I'm not very clever:
> However, since this should be a shared piece of application data AND a download-able piece of user data, 

It is certainly the former, but not the latter. Like I mentioned in the other thread, my understanding is that this should be considered as no more downloadable than, say, `topics.json`. It only changes when releases are made. Is that wrong? Perhaps @jamalex or @aronasorman could weigh in?

> we need a condition that checks if the installation already provides bundled-in application data in a system-wide directory, kalite.ROOT_DATA_PATH.

Are you saying we need to look for application data (as opposed to user data) in a directory which might be separate still form the installation directory? So then there are three classes of data:
* User data
* Unshared application data (the source)
* Shared application data (assessment.sqlite... and anything else?)

I could see the benefit of having such data separated from the source, but up to this point I had simply never considered the idea.

**Comment by 66eli77** [comment]
It's desirable if kalite can read content from two different locations(one default, one assigned), so that user can insert a SD card with some content(assigned) and also be able to use content on the default location(this is the location where using kalite's video downloading page will save to)
Current behavior on android is that if user assigned a location to read content, the user won't be able to access any content downloaded from the video downloading page.

**Comment by MCGallaspy** [comment]
@66eli77 that's a good point, so you're saying that we should distinguish between application data, default system data (kind of like user data), and user data (which supersedes system data if it exists)?

**Comment by 66eli77** [comment]
@MCGallaspy I realize I was talking about a slightly different concern, which is more about contents(videos)

**Comment by 66eli77** [comment]
But distinguishing these data will make our platform more flexible, which is a nice characteristic, given our platform will be installed on different devices, the runtime environment is less predictable.

**Comment by benjaoming** [comment]
What we currently call "assessment items" also curtail content.json and thumbnails of videos. It's ~0.5 GB.

This can be bundled with an installer or downloaded by running `kalite manage setup`.

There's a system-wide path (in `sys.prefrix`) and a user data path (in `KALITE_HOME`). The latter will take precedence.

**Comment by benjaoming** [comment]
This is fixed
