### ISSUE TITLE
"← Back to Facilities" link on User report page

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3927]
Maybe there is some reason why the Learner should have a way to access the Facilities that I am unaware of. In that case, close the issue... 

**Branch**: today's develop  

**Current Behavior**: When Learner goes to see their Progress report, there is a **← Back to Facilities** link in the upper left corner:

![back-to-facilities](https://cloud.githubusercontent.com/assets/1457929/8332610/1f99e56c-1a8f-11e5-9a78-864e1eb98eca.png)

If they follow the link, they end up on the homepage with the authorization alert:

![account-authorized](https://cloud.githubusercontent.com/assets/1457929/8332648/4f97ba8c-1a8f-11e5-8d70-0076ba003e50.png)
  
**Expected Behavior**: If a Learner is not authorized to see the Facilities page, they should not see the **← Back to Facilities** link.

**Steps to reproduce**:

1. Log in as Learner.
2. Go to **My Progress** in the user dropdown.

**Comment by jtamiace** [comment]
That should definitely not be there for learners. 

I also had a question about the "back to facilities" link. This progress report page is accessible from both the coach reports page and from the facilities page. If a user is on the coach reports page and they click into a students progress report, it's a bit confusing if they click on this back button and end up not back to the coach report page. 

Based on the various feedback that I've heard from your trips to India, it seems like teachers are more likely to be using the coach report page than they are to be on the facilities page, so it might make more sense to have the back button lead to coach reports?

Otherwise, I guess it would be ideal if it's possible to have the back button take them to the page they were just previously on.

**Comment by radinamatic** [comment]
Fixed in #4086.
