### ISSUE TITLE
pop up message keeps showing up

### ISSUE THREAD

**Issue by rkurata** [learningequality/ka-lite#3984]
I was doing one of the math lessons and what seemed like a hint message kept showing up after I completed each problem. Here's an image showing which lesson I was working on:
![image](https://cloud.githubusercontent.com/assets/10429889/8488713/96a7bae0-20c9-11e5-85da-ab0aa45a3512.png)

I'm referring to the "an integer, like 6" message shown below

![capture](https://cloud.githubusercontent.com/assets/10429889/8488681/55a4761e-20c9-11e5-9b61-9c5abddcf9f6.PNG)

I also noticed before that this pop up message was also showing up on top of the lesson menu.

**Comment by rkurata** [comment]
I just realized that the message is probably supposed to be there, but I do think it might be unnecessary for it to appear for every problem.

**Comment by jtamiace** [comment]
I agree that it should not automatically pop up for every problem; the help box appears when the input box is active/clicked on.

One solution is to load the page with the input box inactive, so that the box only appears if they click on the input box. However, this still creates the same issue that Rachel brought up. 

Another solution is to make a "help button" next to the input box represented as a "?" icon or something, so that seeing this information is optional. 

I was going to suggest hiding this altogether but then I saw an exercise like this: 
![tooltip](https://cloud.githubusercontent.com/assets/6668144/8505525/74f2177c-219d-11e5-9e62-b6c6c5460146.PNG)

where there are complex operations needed to answer that may not be immediately apparent to the learner. 

The quick fix for now can be the first solution I suggested, but I think the second solution I suggested can be punted to 0.15 unless it seems viable to be able to finish before the 0.14 relase. I'm guessing that this would just entail attaching whatever "help" backbone view appears here to a new icon rather than the input box? 

Any thoughts @rtibbles ?

**Comment by radinamatic** [comment]
If I understand correctly, the 'popup' message is created by `qtip` script in Perseus exercises, with the purpose of giving 'tips' to learners regarding the required answer format. As @jtamiace mentioned, `qtip` appears on almost all answer input fields that are in focus, and the first one, by default, gains focus on page load.

Personally I don't find them distracting, and I see some potential concerns from the accessibility point of view, should we decide to make them "inactive":

- the present situation is most beneficial to sighted keyboard users, as it focuses immediately on the field that requires them to input the answer and saves them several TAB key presses they would otherwise need to arrive to it.

- blind keyboard & screen reader users do not fare so well as the content of `qtip` for the first form field (input, check box, etc...) is read immediately on page load. However, most of the math Perseus exercises are inherently inaccessible to blind users, and it is not something that can be addressed in the short run.

**Comment by radinamatic** [comment]
Two more opinion in favor of NOT setting a form field as focused by default on page load:

[Does accessibility require that focus be set to page content on page load?](http://theaccesspond.com/2012/03/29/does-accessibility-require-that-focus-be-set-to-page-content-on-page-load/)  

[Accessibility - Keyboard Focus order - tab directly to form or tab through all elements?](http://ux.stackexchange.com/questions/56098/accessibility-keyboard-focus-order-tab-directly-to-form-or-tab-through-all-e)

**Comment by rtibbles** [comment]
Not clear to me that discussion on how to resolve this issue is finalized. Punting.

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.
