### ISSUE TITLE
Screenshots in documentation can have footer and whitespace removed

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4242]
Would be great to:
- Remove the footer from screenshots
- Remove dead whitespace from screenshots
- Add a border around screenshots so they're more clearly delineated (since they share a BG color with the docs page)
- Force a newline before screenshots so they don't sometimes get stuck at the end of a line of text (zoom out to see this happen)

![image](https://cloud.githubusercontent.com/assets/618416/9279078/e1360a00-4269-11e5-8f62-ae4caff58cc8.png)

**Comment by MCGallaspy** [comment]
Noted, adding this to the table for 0.16. (Right now it's in spooky task limbo.)

**Comment by benjaoming** [comment]
Screenshots may be auto-generated, provided that the `screenshots` command works. However, as we are going to switch to a more steady development, a.k.a. "legacy mode", we might as well just refine all screenshots manually.

Furthermore, footers read the wrong version number as they haven't been regenerated since 0.17.
