### ISSUE TITLE
Document the "kalite" command

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4326]
We don't have anything in the docs regarding the existence of the "kalite" command, or how to use it. This is pretty critical, since we've deprecated the old way to do many of these things using `manage.py`.

Some things to document:
- [x] That the command exists
- [x] That `manage.py` is deprecated, and how to do equivalent things via `kalite manage`
- [ ] That it's on the path in Linux/OS X, but needs a more explicit form on Windows (show example)
- [x] List of primary commands, what they do, and when to use them
- [ ] Fix all the many references in the docs to navigating to the installed directory and calling `bin/kalite`, since that's not the recommended approach anymore

**Comment by aronasorman** [comment]
0.17.

**Comment by benjaoming** [comment]
> Fix all the many references in the docs to navigating to the installed directory and calling bin/kalite, since that's not the recommended approach anymore

I only find occurrences remaining in our developer docs, which is fine since they may or may not have installed it with `pip -e .`. Personally, I often end up running stuff with `bin/kalite`.

**Comment by benjaoming** [comment]
This is fixed in #5380

**Comment by benjaoming** [comment]
>  That it's on the path in Linux/OS X, but needs a more explicit form on Windows (show example)

I have written a warning regarding the system services, because they may use a different configuration than invoking `kalite` from command line.

Furthermore, we have a warning message displayed to users running `kalite` from another user than the default Debian user account (`kalite`).

I can't resolve the Windows issue, there seems to be different outcomes depending on whether you are on Windows XP, Vista, 7, 8, 10.... afaik some of them will work.

**Comment by benjaoming** [comment]
The documentation of the `kalite` command is here:

http://ka-lite.readthedocs.io/en/develop/usermanual/cli.html
