### ISSUE TITLE
Exercises pane no longer centered.

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/ka-lite#4418]
**Branch:**  0.15.x

**Expected Behaviour:**  The left pane must align horizontally with the right pane.

**Current Behaviour:** The left pane align odd to the right pane. 
![screenshot 2015-09-11 17 47 07](https://cloud.githubusercontent.com/assets/4099119/9812910/75ece038-58b3-11e5-8cda-47a5134b6861.png)

**Steps to Replicate**
>1.  Navigate to the Learn Tab
>1. Select a topic on the Topic tree
>1. Notice that the exercise page view odd.

**Comment by cpauya** [comment]
@arceduardvincent Just to confirm: For this issue, you used [khan_assessment.zip](https://learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip) instead of `assessment.zip` on the branch `0.15.x`, right?

**Comment by arceduardvincent** [comment]
Hi @cpauya, yeah I used the khan_assessment.zip instead of assessment.zip on the branch 0.15.x then this issue occur.

I change the title above so it will not be confusing.

**Comment by MCGallaspy** [comment]
@rtibbles is it possible to see a diff of the data for this assessment item from the last assessment item zip and the current one? My guess is that's the cause of this issue.

**Comment by rtibbles** [comment]
This has nothing to do with assesment items, as the same styling issue occurs on Khan Exercise exercises.

![image](https://cloud.githubusercontent.com/assets/1680573/9967706/193b78fe-5df9-11e5-9da3-1fc4e933c9c4.png)

The issue here is that the content area view is now styled differently to allow the videos to take up the whole width of the screen if possible, meaning the exercises are now free to float left.

It is the same reason that the message container is now stretched all the way across the screen, when the screen has dimensions that are oddly elongated in width.

![image](https://cloud.githubusercontent.com/assets/1680573/9967775/8c7a32b0-5df9-11e5-924b-570e00c6c784.png)

**Comment by rtibbles** [comment]
Also, this is worse after going to a video then navigating to an exercise:
![image](https://cloud.githubusercontent.com/assets/1680573/9973780/d36d8076-5e2d-11e5-9e4e-0b241df3c587.png)
