### ISSUE TITLE
`kalite start` fails when default port is taken, even if settings specify another port

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4599]
Branch: 0.15.x

`PRODUCTION_PORT = 7007`, and Nginx is running on port 8008.

When trying to run `kalite start`, I get the error:

    Port 8008 is occupied. Please close the process that is using it.

It looks like this message is from kalitectl.py, where it checks whether either a manually specified port (on the command line, with `--port=7007`) or the default port (8008), from:

    # TODO: Can be configured in django settings which is really odd because that's
    # run INSIDE the http server
    DEFAULT_LISTEN_PORT = os.environ.get("KALITE_LISTEN_PORT")

We still support configuring the port from within the Django settings (and even though strange in a typical Django project, it makes sense for KA Lite). So, at least for now, we should continue to respect the `PRODUCTION_PORT` for determining whether a port is taken, during startup.

**Comment by benjaoming** [comment]
`PRODUCTION_PORT` is AFAIK not something that should be set. We need to revisit the docs etc. to see that things haven't become ambiguous or confusing.

To start on 7007:

    kalite start --port=7007

The reason is that the port option has to be known before the django settings stack is loaded.

> So, at least for now, we should continue to respect the PRODUCTION_PORT for determining whether a port is taken, during startup.

Absolutely, well, actually we should just make sure it's gone so that setting the de facto production port happens through `KALITE_LISTEN_PORT` (env var) or `--port`.

We do, however, rely on the `PROXY_PORT` setting, which I think has been left out of the picture by mistake here: https://github.com/learningequality/ka-lite/blob/master/kalitectl.py#L474

**Comment by jamalex** [comment]
> We need to revisit the docs etc.
Specifically, the Raspberry Pi settings module sets it. What's the mechanism for the Pi DEB installer to set the port? The env var?

**Comment by benjaoming** [comment]
It writes it to a specific file `/etc/ka-lite/server_options` which the system service uses to load options for the kalite command. But it could have been an env var as well.

https://github.com/learningequality/installers/blob/master/debian/debian/ka-lite-raspberry-pi.server_options

Why the settings module sets it was just some kind of "oh well let's make sure we set it in case it's used somewhere", but maybe it should just be annihilated for better clarity.

**Comment by benjaoming** [comment]
I'll work on cleaning it up and making sure the docs doesn't contain wrong information + the information about where to access the server will be cleaned up as well.

**Comment by rtibbles** [comment]
Fixed in #4611
