### ISSUE TITLE
How to move database 

### ISSUE THREAD

**Issue by waltonrp** [learningequality/ka-lite#4654]
I have some offline sites that I'd like to upgrade from KA Lite Linux v13 to v15. I'll prepare a new install on a new hard drive. Can you help me with instructions to back up existing v13 db and move it to the v15 install? I'd like users to not loose data.

Thanks,

**Comment by waltonrp** [comment]
I have the instructions for db migration. I'm sure my issue is with the file path I'm entering, can anyone help? See attachment
![screenshot](https://cloud.githubusercontent.com/assets/9379591/10911946/305cc46c-8215-11e5-9de4-2997ab96f18a.png)

**Comment by EdDixon** [comment]
I do think you maybe right. It is likley path related. I need to replicate this ASAP here but, I know that paths where changed in 0.15.0 to accommodate specific users. @benjaoming @MCGallaspy

**Comment by waltonrp** [comment]
I'm going to have to work on this back in the lab. Virginia DOC move to v15 is officially on hold due to the other issue: logon from I.E.

I'll drop the 2 sites back to v14 this week.

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit
Sent from my iPhone

On Nov 3, 2015, at 11:57 AM, Ed Dixon <notifications@github.com<mailto:notifications@github.com>> wrote:


I do think you maybe right. It is likley path related. I need to replicate this ASAP here but, I know that paths where changed in 0.15.0 to accommodate specific users. @benjaoming<https://github.com/benjaoming> @MCGallaspy<https://github.com/MCGallaspy>

**Comment by MCGallaspy** [comment]
Hi @waltonrp. Difficult to say what the issue you're experiencing with the `gitmigrate` command is. Can you provide instructions for how to reliably replicate this?

In the meantime, you may find the following information helpful. In versions 0.13.x, if you cloned the git repo and ran KA lite "from source" from that directory, then the database file with user account data was found nested in the same directory as the source files. For example, if you copied the source from github to `/home/mike/ka-lite` then the database would be at `/home/mike/ka-lite/kalite/database/data.sqlite`.

For upgrading to 0.15.x we have attempted to provide the gitmigrate command to help transition users. Since you appear to be experiencing an error, as a workaround I recommend first installing KA Lite 0.15.x [using these instructions from our official documentation](http://ka-lite.readthedocs.org/en/0.15.x/installguide/install_all.html#main-method-ubuntu-debian-deb). Note in particular that we now no longer support pulling the latest version from github and running from source in version 0.15.x.

Next, as part of installing and running KA Lite 0.15.x using the deb file, you should have selected which user to run KA Lite as. After starting the server for the first time, you will find some data files, including the database in that user's home directory (`~/.kalite/database/data.sqlite`). If you stop the server and copy the *old* database file from the location where you were running 0.13.x (e.g. `/home/mike/ka-lite/kalite/database/data.sqlite`) to the *new* location (e.g. `/home/your_kalite_user/.kalite/database/data.sqlite`) and *then* restart the server, it should detect and use your existing database.

Step by step recap:

1. [Install 0.15.x](http://ka-lite.readthedocs.org/en/0.15.x/installguide/install_all.html#main-method-ubuntu-debian-deb)
2. Stop the 0.15.x server.
3. Copy 0.13.x database file to 0.15.x database location.
4. Restart 0.15.x server.

These instructions come in good faith but with no guarantee: I don't know what the particulars of your setup are. Please back up your data first if it's important to preserve it.

**Comment by MCGallaspy** [comment]
@waltonrp 
On closer inspection it appears the value of the `--git-migrate` option should *not* be the path to the data.sqlite file, but rather the base directory of the KA Lite installation. For example, if I had installed KA Lite 0.13.x to `/home/mike/ka-lite` then I would run the command: `kalite manage setup --git-migrate=/home/mike/ka-lite`.

**Comment by waltonrp** [comment]
Thanks. I picked up on that and tries with the same error. Will send screenshot ASAP

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit
Sent from my iPhone

On Nov 3, 2015, at 2:35 PM, Michael Gallaspy <notifications@github.com<mailto:notifications@github.com>> wrote:


@waltonrp<https://github.com/waltonrp>
On closer inspection it appears the value of the --git-migrate option should not be the path to the data.sqlite file, but rather the base directory of the KA Lite installation. For example, if I had installed KA Lite 0.13.x to /home/mike/ka-lite then I would run the command: kalite manage setup --git-migrate=/home/mike/ka-lite.

**Comment by waltonrp** [comment]
Step by step recap:

    Install 0.15.x
    Stop the 0.15.x server.
    Copy 0.13.x database file to 0.15.x database location.
    Restart 0.15.x server.


This seemed to work fine. I'm attaching details from the GUI. All seems fine with data. That's easy enough.

I attached screen shots from errors on doing it at command line

Thanks and let me know what you think
![migrate](https://cloud.githubusercontent.com/assets/9379591/10923919/7ef5e374-8251-11e5-8faf-5886bc71d32b.png)
![old database folder](https://cloud.githubusercontent.com/assets/9379591/10923922/810b796c-8251-11e5-8c50-5f87b2c08ef6.png)

**Comment by MCGallaspy** [comment]
I'm guessing that you're still specifying an unexpected location for the `--git-migrate` option. If you cloned this repo for 0.13.x, then the directory specified for that option should be the same base directory as this repo (not a subdirectory of this repo). However, if the workaround works for you, I'll close this issue.
