### ISSUE TITLE
KA Lite startup lockfile problems

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4738]
@j-schwartz reported an issue with the startup lock existing after the machine has been powered down and restarted. He's using 0.15.0 on a raspberry pi. [Here's what he said](https://github.com/learningequality/ka-lite/issues/4664#issuecomment-162271089):

hi guys - quick note, and I'll document it better when I can recreate on purpose, but I'm not sure the init issue has been fixed yet. After an unexpected shutdown on the raspberry pi, upon reboot, KA-lite does not reboot and is again hindered by the lock file we were fixing the pp-kalite-clean boot init script we created. see screenshot after a failed shutdown:

![image](https://cloud.githubusercontent.com/assets/8888020/11642346/461737cc-9cf2-11e5-9de0-75b157a92d00.png)

---

Can we replicate this issue?

**Comment by MCGallaspy** [comment]
@benjaoming drawing your attention to this as well

**Comment by benjaoming** [comment]
I would re-state the following:

1. The lock file is created before `initialize_kalite` is called and removed after. This command does migrations, collectstatic etc. So having a lock file there means that kalite was killed during initialization.
1. Since there used to be a script that wiped the .kalite dir, initialization would take place every time the RPi of @j-schwartz was booted. This takes a long time. If he did a reboot again during those minutes, then the lock file would be there, since the ka-lite init script would probably have been killed.

I looked at the way we create and remove the startup lock, and I don't think there's a way around this. There's a reason why we have the lock file: To avoid having the same process trying to migrate and collect static.. we don't want this race condition. So basically, I don't think there's anything further we can do here.

**Comment by j-schwartz** [comment]
Hi guys - just to be totally clear, has this behavior of the lock file changed since 0.13.1?  In 0.13.1 the lock file behavior was a severe problem for us and deployments abroad, most of which (if not all), lost access to KA-Lite within weeks of deployment (despite all other content functioning OK).

**Comment by jamalex** [comment]
Seems like the natural solution would be to have the system startup script (pp-kalite-clean) delete the `/home/pi/.kalite/kalite_startup.lock` (or any other locks) at boot, rather than deleting the entire `/home/pi/.kalite` directory (which now contains other important things, like the database, etc).

**Comment by benjaoming** [comment]
@j-schwartz that sounds severe, and to be honest, it wasn't as well managed back in 0.13.

I was created here: https://github.com/learningequality/ka-lite/blob/0.13.x/kalitectl.py#L341

And then removed in `kaserve` which was a different management command: https://github.com/learningequality/ka-lite/blob/0.13.x/kalite/distributed/management/commands/kaserve.py#L142

But the consequence would still be the same: If you deleted the .kalite directory at every startup, then initializing kalite would take many minutes, and if you would do a reboot during this initialization, then lock file would remain.

Hmm, but I'm thinking about one thing: Namely that the lock file cointains a PID and if that PID is not active, kalite will still start. This was also the case in 0.13: https://github.com/learningequality/ka-lite/blob/0.13.x/kalitectl.py#L331

I don't quite know what to make of this. Maybe that the deployments died because .kalite was deleted and there's a fair chance that the PID of the lock file is in use anyways.

**Comment by benjaoming** [comment]
:+1: for @jamalex's solution, an init script should be allowed to do that.

**Comment by benjaoming** [comment]
No that wasn't a good solution :) I closed the above issue, see comment in there.

**Comment by j-schwartz** [comment]
I got lost a little in the above, so I just want to include straight from our volunteer fix his comments, to make sure we're on the same page:

It turns out that there is a bug in the kalite init script that prevents the lock directory to be removed even when the machine is cleanly shutdown. The kalite startup and shutdown scripts need to be run as Pi. They do not work properly when run as root. The kalite init script is setup to switch to the Pi user when starting the server, but not when shutting down. This causes the init script to fail even on a clean shutdown and not delete the lock file.

i have created a fix for us to use with our images. The fix corrects the bug in the kalite init script so that KA-Lite is shutdown properly on a clean exit. I also added an additional script on boot to delete any left over kalite lock files on startup. This should ensure that KA-Lite can start after unclean shutdowns as well when the kalite shutdown script is never run. I have included the two files that make up my fix below. Feel free to use them or modify them as you see fit for your next release.

NOTE: The scripts assume the following directory structure based on our deployment setup. You will need to duplicate this setup if you want to use the script unmodified:

bin/pp-kalite-fix
etc/init.d/pp-kalite-clean

This included an attached pp-kalite-fix:
```
#!/bin/bash

CMDNAME=$0
PPBIN=`dirname $0`
PPDIR="$PPBIN/.."

if [ `id -u` != "0" ]; then
    echo "$CMDNAME: This script must be run as root"
    exit
fi

install -o root -g root -m 755 $PPDIR/etc/init.d/pp-kalite-clean /etc/init.d
update-rc.d pp-kalite clean defaults

if [ -e /etc/init.d/kalite ]; then
    sed -i 's|"/home/pi/ka-lite/kalite/../bin/kalite stop"|su `stat --format="%U" "/home/pi/ka-lite/kalite/.."` -c "/home/pi/ka-lite/kalite/../bin/kalite stop"|' /etc/init.d/kalite
fi
```

and an attached pp-kalite-clean

```
#!/bin/sh
# pp-kalite-clean	Clean up KA-Lite lock files on boot

### BEGIN INIT INFO
# Provides:          pp-kalite-clean
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     S
# Default-Stop:
### END INIT INFO

. /lib/lsb/init-functions

case $1 in
    start|clean)
	log_action_begin_msg "Cleaning up KA-Lite lock files"
	rm -rf /home/pi/.kalite
	log_action_end_msg 0
	;;
    restart|reload|stop)
	;;
    status)
	if [ -e /home/pi/.kalite ]; then
	    echo "KA-Lite lock directory exists"
	else
	    echo "KA-Lite lock directory does not exist".
	fi
	;;
    *)
	echo "Usage: $0 {start|stop|status|clean}"
	;;
esac
```

I'm going to re-read @benjaoming's post and see if I can follow, just wanted to have this out there so you can confirm I've properly articulated the issue and fix and we are all on the same page with the issue.

**Comment by j-schwartz** [comment]
Also, @benjaoming the deployments that died were before we initiated this fix.  They wouldn't boot ka-lite because of the presence of a lock file.  A totally different deployment team used this fix as an alternative to pp-kalite-fix and pp-kalite-clean:

```
When KA-Lite Quits Running
(All other RACHEL content works, but KA-Lite won’t open)

Need: Rachel Pi, monitor with HDMI port, HDMI cable, Ethernet cable, wireless keyboard/mouse with USB antennae, external battery, laptop computer 
1.	Use the Ethernet cable to connect the Pi to a live network port
2.	Connect Pi to the monitor using HDMI cable
3.	Insert into the PI the keyboard/mouse USB wireless antenna
4.	Plug battery cable into the Pi, and press the ON button on the battery. This will start the Pi.
5.	The boot up script should show on the monitor (if not, toggle the Input to HDMI)
6.	Connect the laptop to the RPI wireless signal
7.	When the boot up script on the monitor completed, login to Rachel with username = pi, password = rachel (will not show on screen)
8.	At the $ prompt enter:  sudo  chown  -R  pi:pi  /home/pi/ka-lite <Enter>
9.	Stop kalite  I’m not sure the exact command, but I think it’s simply stop
10.	At the $ prompt enter:  -rf  /home/pi/.kalite <Enter>  This removes the lock
11.	At the $ prompt enter:  sudo  chown   -R  pi:pi  /home/pi/ka-lite <Enter>
12.	At the $ prompt enter:  /home/pi/ka-lite/bin/kalite  start <Enter>
```

**Comment by benjaoming** [comment]
> It turns out that there is a bug in the kalite init script that prevents the lock directory to be removed even when the machine is cleanly shutdown. The kalite startup and shutdown scripts need to be run as Pi. They do not work properly when run as root. The kalite init script is setup to switch to the Pi user when starting the server, but not when shutting down. This causes the init script to fail even on a clean shutdown and not delete the lock file.

@j-schwartz the init script that's distributed with the .deb does switch to the configured user:

https://github.com/learningequality/installers/blob/master/debian/debian/init-service#L36

**Comment by benjaoming** [comment]
> This included an attached pp-kalite-fix:

(snip)

>     sed -i 's|"/home/pi/ka-lite/kalite/../bin/kalite stop"|su `stat --format="%U" "/home/pi/ka-lite/kalite/.."` -c "/home/pi/ka-lite/kalite/../bin/kalite stop"|' /etc/init.d/kalite

This fixes something in the previous version of the init script, the one generated from `kalite manage initdconfig`: https://github.com/learningequality/ka-lite/blob/0.13.x/kalite/distributed/management/commands/initdconfig.py#L34

**Comment by j-schwartz** [comment]
Perfect. So it sounds like I am good to go with 0.15 without any sort of additional scripting of the lock file.  Thank you guys!

**Comment by benjaoming** [comment]
@j-schwartz I hope so. I mean, in theory then there are still problems if kalite is forcibly killed while initializing and the same PID is still in use when it starts. But the likeliness seems little since you're not deleting the whole .kalite folder anymore during startup.

**Comment by benjaoming** [comment]
@j-schwartz Are you guys going to do upgrades from 0.13 to 0.15 in any deployments?

**Comment by j-schwartz** [comment]
@benjaoming we got a process down, but 'moving' videos into .kalite/content causes them to be recognized by the videoscan, but still grayed out in the user interface.  I need to try one where I use settings.py to ask kalite 0.15 to grab videos from the old ka-lite/content folder (without actually moving videos) and see if that fixes the issue.

**Comment by MCGallaspy** [comment]
Hi @j-schwartz, it would be immensely useful if you created issues for situations like that -- we want to be able to address those problems for everyone, since it's likely you're not the only one to have that problem.

**Comment by j-schwartz** [comment]
@MCGallaspy I'll be more liberal about that. It's 100% because I'm never really sure what I'm talking about when things get too technical.  I have it on a note to investigate a little further so I can give better details, and then check and see if it's not dumb user error (permissions or something) first.  I do get lost a little though, so apologies I haven't been more liberal in setting up 'issues' here.

**Comment by MCGallaspy** [comment]
Your caution is certainly appreciated.

**Comment by benjaoming** [comment]
@j-schwartz you've got a pretty decent track record of reporting legitimate issues so please go ahead with the liberal issue creating :D

**Comment by EdDixon** [comment]
@radinamatic @mike IMHO this issue should definitely be added to release testing scenarios. It is one I have not been checking for and is critical to many deployments.

**Comment by benjaoming** [comment]
@EdDixon you mean you want to start rebooting to check that the system service still runs after a reboot?

**Comment by EdDixon** [comment]
@benjaoming no, that videos get listed properly when added to the content folder manually.

**Comment by benjaoming** [comment]
@EdDixon yeah, definitely what's reported is that our automatic tests haven't spotted something critical.

**Comment by 3kay** [comment]
I am having a similar problem with a 0.15 installation on a Raspberry Pi. I had earlier downloaded resized videos in bulk and tried to use the folder in a usb stick plugged into raspberry pi with a soft link from ./kalite/content . I see all videos grayed out. When I try video download in management, I see all dots for topics fully green and no check boxes available for downloading any videos through the ka-lite interface.
The same videos are working fine in an ubuntu installation on a laptop.

**Comment by MCGallaspy** [comment]
@3kay thanks for the info, I'm opening a new issue. Please check it out and provide additional information if possible.
