### ISSUE TITLE
Manage tab is missing videos and languages subtab

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#4760]
branch: 0.16.x

![screen shot 2015-12-15 at 11 43 19](https://cloud.githubusercontent.com/assets/191955/11821987/2075ac44-a321-11e5-8159-817107158c6f.png)

Can't download videos, can't change language, can't do nothin.

**Comment by aronasorman** [comment]
This is blocking my content pack development. Taking this.

**Comment by j-schwartz** [comment]
Riddle me this, my 0.15.0, is missing this also.  I had a local downloaded copy of 0.15.0 which was working fine for some time (rather than pulling from KA-Lite, I was pulling a download locally).  This is that same local copy being installed on a raspberry pi yesterday, and it is missing those tabs.

![image](https://cloud.githubusercontent.com/assets/9270388/11985106/4d78a1d2-a976-11e5-8b52-e64f5ad04a4c.png)

**Comment by rtibbles** [comment]
@aronasorman @j-schwartz Can you do a Javascript console dump (F12, click on 'console' tab) to show what might be happening here?

**Comment by MCGallaspy** [comment]
@aronasorman did you fix this?

**Comment by radinamatic** [comment]
My 0.16 shows both tabs, so it's probably fixed! @MCGallaspy
