### ISSUE TITLE
Spanish content and assessments: What's available? Bulk Download?

### ISSUE THREAD

**Issue by edresor** [learningequality/ka-lite#4816]
I am a non-Spanish speaker trying to help someone going to Costa Rica with servers, which he wants to switch from English to Spanish.
1.) If he checks Khan Academy https://es.khanacademy.org/  will most of the Spanish Lessons there be downloadable into KA-LIte?
2.) What is the status of assessments in Spanish?
3.) Should he use the regular .deb file for an Ubuntu server?
4.) Is there a place to download some of the Spanish videos in bulk?

Thanks.  Sorry if I missed this in the documentation.

**Comment by MCGallaspy** [comment]
> If he checks Khan Academy https://es.khanacademy.org/ will most of the Spanish Lessons there be downloadable into KA-LIte?

The availability of Khan Academy content in KA LIte is tied to our release schedule -- generally we update content once per major release, since updating content is pretty resource intensive. @rtibbles any comments about this?

> What is the status of assessments in Spanish?

Not sure, @rtibbles or @aronasorman?

>Should he use the regular .deb file for an Ubuntu server?

Yes

> Is there a place to download some of the Spanish videos in bulk?

[Is this what you're looking for?](http://ka-lite.readthedocs.org/en/latest/faq.html#is-there-somewhere-i-can-find-spanish-language-content-organized-by-topic)

**Comment by edresor** [comment]
Yes.  I thought I had seen it, but I could not remember if it was just subtitles.
Thanks
