### ISSUE TITLE
Videos Out of Sync between Learn and Update tabs

### ISSUE THREAD

**Issue by j-schwartz** [learningequality/ka-lite#4835]
Hi Guys,

Discovering something a bit quirky. 0.15.1 on a linux deb.  This is a Spanish build.

After downloading all available videos through the KA-Lite interface, I still have greyed out videos in the learn tab.

![image](https://cloud.githubusercontent.com/assets/9270388/12990244/37c36024-d0be-11e5-8820-1c2df323a5e8.png)

Said another way, there are videos listed in the learn tab which are not also included in the manage / update videos tab for download.  In fact, the entire sub groups of Contando numeros pequenos and contando objectos don't exist

![image](https://cloud.githubusercontent.com/assets/9270388/12990401/1023939e-d0bf-11e5-9391-55e5fecd182f.png)

As an example, the first section of early math cc-early-math-counting-topic/cc-early-math-counting/ has two videos in Spanish "Contar con numeros pequenos" and "Contar en orden" listed by the learn menu.  These video files on the Khan Academy Spanish You Tube channel are title fEgh1fi_pyQ and UkGIKRPafII
```
 https://es.khanacademy.org/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/v/counting-in-order
```

Any thoughts on how to update the manage/videos list to include options to download all the videos that are included on the learn menu?

**Comment by j-schwartz** [comment]
Just investigating this a little more, somewhere along the line "Contar en orden" on the http://es.khanacademy.org site becomes "contando en orden" when getting to youtube.  Manually downloading "contando en orden" from youtube and dropping it in the KA-Lite content folder as "UkGIKRPafII" does not work

**Comment by MCGallaspy** [comment]
Thanks again for the detailed report!

**Comment by j-schwartz** [comment]
No problem, but just as a for what it's worth, it looks as though the majority of videos in Spanish are running into this issue.  

Just checking through "early-math "/ "Contando"   8 out of 11 videos are missing because of this issue.  

That's my way of hoping this can be a 0.16 thing vs a 0.17 thing.

**Comment by MCGallaspy** [comment]
Okay, I'll see what I can do!

**Comment by j-schwartz** [comment]
Thanks, if there is something I can do from here to help, please let me know.

**Comment by rtibbles** [comment]
This is due to the use of disk based content caches on the Raspberry Pi - these caches need to be deleted when content is manually copied in.

To do this:

To delete the files named topics from this filepath:
in django_settings.USER_DATA_ROOT in the 'cache' folder.

 and the sqlite db from this one: from the 'channel_cache_data' also in the django_settings.USER_DATA_ROOT.

**Comment by j-schwartz** [comment]
Thanks, @rtibbles.  Can you help me in locating the files you mention.  I don't have a 'cache' folder in my .kalite install and am not sure I'm tracking your right on the location for these files.

Within my install at /root/.kalite I have the following:
![image](https://cloud.githubusercontent.com/assets/9270388/13090676/0e6ec91a-d4ac-11e5-988b-a341cfc669db.png)

At /usr/share/kalite/python-packages/django I have the following:
![image](https://cloud.githubusercontent.com/assets/9270388/13090696/223452c6-d4ac-11e5-8916-42733e188ca5.png)

The command run from /of 

```
fine . -name django_settings\*
```

draws a blank for me.  Any additional help would be appreciated!

**Comment by rtibbles** [comment]
Odd - the only other place I can think of it being would be in `user/share/kalite`, is there a `cache` or `channel_cache_data` folder in there?

**Comment by j-schwartz** [comment]
Nothing there that I can see:

![image](https://cloud.githubusercontent.com/assets/9270388/13090940/9b3f22ee-d4ad-11e5-97b3-7783fa6d7fb8.png)


The channel_cache_data folder is definitely there in my first picture at /root/.kalite/ but there aren't any files inside it. 

Just to confirm, the file supposed is to be named starting with django_settings?

**Comment by rtibbles** [comment]
No, the files would be called topics_khan_en.json (or topics_khan_<lang_code>.json) and contents.sqlite.

**Comment by j-schwartz** [comment]
I have a topics.json and a contents.json in /usr/share/kalite/data/khan/.

The only .sqlite files I have are
assessmentitems.sqlite and data.sqlite

[image: pasted1]

Any of that seem helpful?

**Comment by rtibbles** [comment]
No, these files are generated from the json files to improve startup time on the Raspberry Pi.

This might take a while to search the whole file system, but could you try doing:
`find / -name 'topics_khan_es.json'`?

Assuming this is still on the Spanish content system above.

**Comment by j-schwartz** [comment]
No luck with this.  It doesn't take long as ka-lite is the only installed
software beyond raspbian Jessie at this point.

**Comment by rtibbles** [comment]
Hrm... could you try the following?

`kalite manage shell` - this will open up a Python shell, in it enter the following commands:

```
from kalite.topic_tools import settings
settings.CONTENT_CACHE_FILEPATH
```
This should print the filepath where the sqlite file should be found.

```
from django.conf import settings as django_settings
django_settings.USER_DATA_ROOT
```
This should show where the 'cache' folder should be found.

**Comment by j-schwartz** [comment]
Totally perplexed, as the answers point to exactly where you originally mentioned, but I still don't see anything using 
```
ls -al
```
![image](https://cloud.githubusercontent.com/assets/9270388/13094104/91fbac9c-d4bd-11e5-9589-cde5048ee4f6.png)

searching directories
![image](https://cloud.githubusercontent.com/assets/9270388/13094113/9e86b04c-d4bd-11e5-8745-e6312f9a77db.png)

**Comment by rtibbles** [comment]
My only other suggestion would be to do: `rm -R cache`, `rm -R channel_cache_data` to just remove the directories and see if that made any difference.

**Comment by j-schwartz** [comment]
It didn't appear to do anything, but I'm wondering if maybe it has to do with the en topic tree loading also?  Is there a way to just have spanish start at boot?

![image](https://cloud.githubusercontent.com/assets/9270388/13094581/6fecfe82-d4c0-11e5-9b26-9047583a4332.png)

**Comment by rtibbles** [comment]
Yeah, the first load with no topic tree files will be incredibly slow.

I am not sure we currently have a way to prevent the English annotation
happening, unfortunately.

**Comment by j-schwartz** [comment]
Same issues after deleting cache and channel_cache_data folders for me.

**Comment by j-schwartz** [comment]
@rtibbles -  just for what it's worth, I have the same issues with content mismatch between available video downloads and the learn tab on a clean install also.

**Comment by rtibbles** [comment]
Thank @j-schwartz - the complete absence of the cache files is the thing that is still confusing me. It must be reading them from somewhere, but if they are not there, I am not sure where it is reading it from.

**Comment by needlestack** [comment]
In case anyone else is having similar troubles, here's what I've found digging into this:

1) Caching - I found that our system was not disk caching because of our startup settings - to get disk caching we needed to start with: `kalite start --settings=kalite.project.settings.raspberry_pi`. I do not know how that would affect non raspi systems. Specifically, caching seems to be enabled by setting the constant `DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP = True`, which instructs kalite to keep the disk cache at startup instead of refreshing it. However it seems that setting this to `False` (the default) prevents all disk caching, not just refreshing at startup.

With caching enabled we see our startup time drop from 10 minutes to 30 seconds (except on the very first launch).

2) Missing videos - These appear to be videos that were not translated at the time of 0.15's release. So they are missing from the `locale/dubbed_video_mappings.json`. The result is that you can't download them, and even if you do kalite won't know what they are.

About 200 videos have been translated since 0.15 was released so a new `locale/dubbed_video_mappings.json` file can help. I have attached one that I made as of 2016-03-30. 

[dubbed_video_mappings.json.zip](https://github.com/learningequality/ka-lite/files/197825/dubbed_video_mappings.json.zip)

If you drop this in `locale/` in django_settings.USER_DATA_ROOT, it should allow you to download the 200 new Spanish translations.  That won't do anything about the remaining several thousand untranslated videos, but it's a start.

One last thing: when I enabled the cache after updating `dubbed_video_mappings.json`, the video pages were blank (depsite browsing the tree working). So we've disabled cache for now anyway. Then the new videos work as expected.

**Comment by benjaoming** [comment]
The buggy caching has been replaced. Since we changed to content packs and the new content SQLite dbs in which the database's `items.available` column immediately updates once a new video is fetched.

Please feel encouraged to open up a new issue if any of the reported behaviors persist!

@cpauya btw notice the dubbed video mappings contributed by @needlestack
