### ISSUE TITLE
Raspbian Jessie and Nginx

### ISSUE THREAD

**Issue by SkaeX** [learningequality/ka-lite#4852]
Hello,
I was trying to install KA-Lite 0.15.1 on raspbian jessie, but after following all the instructions on the documentation page, the service always fails with service.kalite failed. After googling, the closest i got was an issue with nginx. Help me out please.

Thanks

**Comment by SkaeX** [comment]
It says precisely Job for ka-lite.service failed. See 'systemctl status ka-lite.service' and 'journalctl -xn' for details. The output of systemctl: ka-lite.service - LSB: ka-lite daemon, a local Khna Academy content server.
Loaded: loaded (/etc/init.d/ka-lite)
Active: failed (Result: exit-code) since Tue *****
Process: 2058 ExecStart:/etc/init.d/ka-lite start (code exited. status: 1/FAILURE)

**Comment by MCGallaspy** [comment]
Thanks for the report @SkaeX, we'll look in to it! I think we have some known issues with 0.15.1 on raspbian jessie, is that correct @benjaoming?

**Comment by benjaoming** [comment]
Correct and confirmed.

learningequality/installers#271

**Comment by benjaoming** [comment]
@SkaeX thanks for the report btw, we're aware of this problem. We tried creating a system service that was as backwards compatible as possible, but this compatibility is now being dropped by new versions of Debian, so we should get rid of it, too. The issue is tracked in our other repo, pertaining our debian packaging.
