### ISSUE TITLE
Video download: Are we.... Counting in numbers? :)

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4929]
## Summary

It seems something's wrong. When selecting videos for download, firstly there's one figure, but then when the download starts, the figure jumps.

I've tried starting downloads, canceling and then starting again. The behavior isn't affected by this, so I don't think it's the download queue that's being over-populated by multiple clicks.

## Branch or installer method

 - Installer: Debian
 - Version: 0.16a4

## Screenshots

![screenshot from 2016-02-27 21 00 11](https://cloud.githubusercontent.com/assets/374612/13375043/e0bd813a-dd95-11e5-8032-0e2c1b8363d5.png)

![screenshot from 2016-02-27 21 00 24](https://cloud.githubusercontent.com/assets/374612/13375042/db13a124-dd95-11e5-82d3-7d551fd8d7fb.png)

**Comment by benjaoming** [comment]
An easier way to spot the problem is that in topics marked as fully downloaded, there are invisible videos counted when marking them,....

![screenshot from 2016-02-29 13 10 56](https://cloud.githubusercontent.com/assets/374612/13394109/5a497c92-dee6-11e5-9522-365e220e7b44.png)

**Comment by benjaoming** [comment]
But I'm actually not sure if that's related at all to the original issue.

**Comment by radinamatic** [comment]
Something is definitely fishy in the manner of counting those videos... :confused: 

Fresh 0.16 (build 66) on OSX El Capitan, selecting the whole `Addition and subtraction topic` said it was 8 videos, but once started the download it's getting 10 from somewhere:

![video_download_el_capitan](https://cloud.githubusercontent.com/assets/1457929/13395342/82c20c18-deee-11e5-9bcb-f0b80a5c8d1f.png)

Seems as if topic tree reloads and appears empty during download, but even after the `Successfully...` message:

![video_download2_el_capitan](https://cloud.githubusercontent.com/assets/1457929/13395405/d154c62c-deee-11e5-9c1b-3eb90350f698.png)

If the whole topic is downloaded (8 or 10 videos), it should have a green marker, right?

But if I re-select the topic at this point, it still does not seem to register that all the videos in it are already downloaded, so it offers the option to download them again:

![video_download4_el_capitan](https://cloud.githubusercontent.com/assets/1457929/13395482/48df25e8-deef-11e5-8812-d13d863c0862.png)

Only after reloading the page (topic tree), it does register something, but erroneously, since it offers to download and delete, as noted by  @benjaoming:

![video_download5_el_capitan](https://cloud.githubusercontent.com/assets/1457929/13395628/49ea9ffc-def0-11e5-8b4c-e7dabc8de591.png)

I'm not sure about the 8-or-10 conundrum, but at least one part of this problem should be fixed by making sure the green marker registers correctly that all the videos inside have been downloaded.

**Comment by rtibbles** [comment]
I can think of a discrepancy occurring in one direction (i.e. you choose to download a certain number of videos, it counts up those videos, and the total number of videos is *less* than that, because there are duplicates across the topic tree. Finding it odd that there might be more videos than you click.

@radinamatic is the flagging of the topic tree icons a consistent bug, or only sometimes?

**Comment by radinamatic** [comment]
Sometimes it counts correctly the number of videos to download, for example in `Early math > Counting` topic, but behaves the same after the download: offers to re-download if the topic tree has not reloaded in the meantime. 

I'm retesting now the `Early math > Addition and subtraction intro` video download on build 154 for Windows, and it behaves the same as this morning on OSX, so I'd say it's pretty consistent @rtibbles  

If I actually decide to re-download, I get the `TypeError: e is null`:

![e-is-null](https://cloud.githubusercontent.com/assets/1457929/13403540/ca66616e-df15-11e5-94f7-b021173cb40b.png)

I'd say this is an error too: if I select the whole group `Addition and subtraction intro` and **only then open** the folder, the subfolders do not seem selected: 
 
![selection_242](https://cloud.githubusercontent.com/assets/1457929/13403517/a879904e-df15-11e5-9c5a-5f46d4e996d6.png)

**Comment by rtibbles** [comment]
Yeah, seeing the difference here - '28 videos to download' then 906 come into the download queue.

Quite a disparity!

**Comment by rtibbles** [comment]
Also, very interesting that I have -7 videos to download.

Something is rotten in the state of Denmark - well, not Denmark, this issue came right out of San Diego, but Shakespeare never wrote a play about San Diego.

**Comment by benjaoming** [comment]
Yes, something is very rotten in the state of Denmark, and we don't even have to bring in Shakespeare fiction, the current government provides plenty. I can open up an issue for that, but I'm afraid it won't get solved by means of offline software solutions :)

**Comment by rtibbles** [comment]
I am doing a deep dive on the video downloading issues now!

**Comment by rtibbles** [comment]
I think this is due to an issue in the content pack maker side, videos were only getting included in the totals if they were also in a topic that contained exercises. This meant that Mathematics had much closer to an accurate count, because it has a lot of exercises, whereas Science was waaaaay off.

**Comment by rtibbles** [comment]
This is fixed in https://github.com/fle-internal/content-pack-maker/commit/00d88694fb767898ac765ac20d87e670ff408807

**Comment by benjaoming** [comment]
pinging @aronasorman ... because I guess it means all content packs need
rebuilding? Could you notify back when it's done?

**Comment by aronasorman** [comment]
They've been rebuilt yesterday PST, so the one on pantry should include the fix linked by Richard.

**Comment by benjaoming** [comment]
Awesome, thanks, gonna enjoy this!
