### ISSUE TITLE
Changes in content.handlebars not being reflected on portal

### ISSUE THREAD

**Issue by Kevsy** [learningequality/ka-lite#5038]
## Summary

I'm trying to add a 'Download this video' link in content.handlebars, but it seems that whatever I add there is not reflected on the page (even random text next to the {{title}} for example).. I've run kalite manage cache clearweb , refreshed the browser but no luck. Is there anywhere else I need to flush to see the change? Thanks!

This is v0.15 on Windows 7.

**Comment by MCGallaspy** [comment]
Hi @Kevsy, sounds like you've installed KA Lite using the Windows installer, and modified the source? Changes to javascript source need to be updated with our build system before it can be reflected in the app. To get started developing KA Lite, please follow the ["Getting Started" instructions](https://github.com/learningequality/ka-lite/wiki/Getting-started), though I recommend working on the `0.16.x` branch instead of the `develop` branch, in contrast to those instructions just now.

**Comment by Kevsy** [comment]
Yes, that's exactly it - thanks for the help!
