### ISSUE TITLE
ka-lite 0.16.1 on RPi3

### ISSUE THREAD

**Issue by 3kay** [learningequality/ka-lite#5080]
Deleted

**Comment by benjaoming** [comment]
Hi @3kay 

Thanks for testing stuff. Indeed, the RPI .deb package is the intended install media for the RPI, and we won't expect the vanilla source to run because of memory issues serving media files in the default cherrypy server.

As for the script that configures the network on RPI: I don't know if it works, neither do I think it's a good idea to use since it wasn't intended/tested for Raspian Jessie.

I would suggest we start discouraging the use of our RPI scripts and possibly delete these repos entirely as they are slightly misleading, @aronasorman @jamalex what do you think?

**Comment by 3kay** [comment]
@benjaoming Thanks for your prompt reply. I think removing this line from Installation Guide would be enough:
"After installing, you can setup a Wifi hotspot using this guide: Raspberry Pi Wi-Fi"
RPI scripts may still be needed if someone wants to install an older version on  RPi A or B series.  I tried to use these because I was installing from a source file.
Will try the .deb version soon.
@aronasorman @jamalex

**Comment by 3kay** [comment]
@benjaoming , @aronasorman , @jamalex 
My sincere congratulations on the release of 0.16. I tried it just now and every thing worked smoothly till the end of the installation process. I did a fresh installation of assessment.zip. I was able to create the admin account and got successfully registered.  Surfing around in exercises was successful.  
I issued the command $sudo halt, switched off the pi, inserted a USB stick with the previously downloaded videos and switched on the pi again. I created a soft link to redirect the 'content' folder to the videos on the usb stick. When I tried to run kalite start again, I received the message:

Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...

Port 8008 is occupied. Please close the process that is using it.

'kalite status' produced:

Unclean shutdown (7)

I think I should have first stopped kalite properly and then shutdown the pi.
Could you please help me in recovering the system back to normal? 
Congratulations once again on the great work you guys are doing.

**Comment by benjaoming** [comment]
@3kay thanks :)

The "8008 port occupied" is saying that KA Lite is already running, so I suspect it could be a mixup of the auto-configured system service, nginx (which runs on 8008) and a manual command.

To stop and start the ka-lite-raspberry-pi service, you should use the system service:

    sudo service ka-lite [start / stop / restart]

The unclean shutdown status is probably because you're running a kalite that expects 8008 to be free, while the nginx service is blocking it with non of the usual kalite runtime data available.

**Comment by 3kay** [comment]
@benjaoming ,
Thanks - the problem of start stop is over and I can successfully do that but now i am faced with two more problems.
1. The built-in wifi adapter of RPi3 is not configured - i did not run the scripts as advised earlier - how do i configure that.
2. Videos are not showing up in the interface although I have created the soft link to the previously bulk downloaded videos on a USB stick. When I remove the link and allow test videos to be downloaded by launching the downloading in the interface - it does show the progress bar and the percent download successfully going but nothing comes to the .kalite/content folder. The server.log shows a lot of errors with the tail:
[INFO] [2016-04-09 18:35:16,379] kalite: Running 1 due jobs... ("Secure Sync")
[ERROR] [2016-04-09 18:38:46,571] root: Thumbnail was not found, tried: http://kalite.learningequality.org/download/videos/HnHCQ2X_meg.mp4/HnHCQ2X_meg.png
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/fle_utils/videos.py", line 51, in download_video
    raise URLNotFound("Thumbnail was not found, tried: {}".format(thumb_url))
URLNotFound: Thumbnail was not found, tried: http://kalite.learningequality.org/download/videos/HnHCQ2X_meg.mp4/HnHCQ2X_meg.png

**Comment by benjaoming** [comment]
@3kay 
> 2. Videos are not showing up in the interface although I have created the soft link to the previously bulk downloaded videos on a USB stick.****

I would advice that you try logging in as the user that kalite is running as, to see if this user has permissions.

If you are running with the default `kalite` user, you can get a command line with the user's permissions like this:

    sudo su kalite -s /bin/bash

Try the doing something like `cd /path/to/videos` and `ls name_of_file.mp4` to see if you have permission issues.

Regarding the missing thumbnails, I'm not entirely sure. Could you assist me by telling me exactly what steps you've been doing? It looks like this is an error during video download.. somehow you probably have a possibly old job queue with videos scheduled for download using an outdated version of the topic database....
