### ISSUE TITLE
No internet connection after setting it up

### ISSUE THREAD

**Issue by pateljj04** [learningequality/ka-lite#5081]
I have it setup and able to connect clients to the kalite but I am not able to download any content since all  internet traffic gets routed to 1.1.1.1 even when I have ethernet plugged in. Not sure what I am doing wrong.

**Comment by Aypak** [comment]
Hi, I assume you're either using ubuntu or a raspberry pi. What's happening is due to a package called dnsmasq which is installed when creating the access point. This package routes all requests to your server to 1.1.1.1. You can stop dnsmasq with the command `sudo /etc/init.d/dnsmasq stop`, and start it again with  `sudo /etc/init.d/dnsmasq restart` .
I suggest you create bash aliases for these commands so that you can stop dnsmasq before downloading content then bring it up again once you're done

**Comment by pateljj04** [comment]
Thank you! Sorry for asking a silly questions, it wasn't clear in the documentation so I wasn't sure.
