### ISSUE TITLE
'show keypad' button not present on exercises

### ISSUE THREAD

**Issue by Aypak** [learningequality/ka-lite#5103]
I am running ka-lite 0.16.2 on a rpi 2, and accessing it using android tablets with the latest Chrome browser. In previous versions of ka-lite(e.g v0.12, 0.15.x) there was a 'show keypad' button on the exercises which would make it easier for the student to enter their answer especially on a touch screen. This button doesn't appear on any of the exercises on the current version. I have observed this behavior also when running the same version of ka-lite using ubuntu 14.04, and even when using different browsers. Has the feature simply been removed or is it most likely a bug?

**Comment by benjaoming** [comment]
@Aypak It seems that it doesn't display on some exercises even though the have input fields.

For instance, it's here: http://localhost:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/counting-objects/

But not here: http://localhost:8008/learn/khan/math/geometry/quadrilaterals-and-polygons/quadrilaterals/quadrilateral_angles/

I'm going to assume we can probably close this as there's no javascript errors on the above, so it appears it doesn't have a keypad because of the design/data of the exercise.

@rtibbles and @aronasorman is this an upstream bug? There doesn't appear to be a Keypad on any of the exercises on the KA.org, so it's hard to know what is really supposed to happen.

**Comment by rtibbles** [comment]
I think this is because the keypad only works reliably with Khan Exercises, not Perseus. Can take a look and see if there is a quick fix.

**Comment by mrpau-eugene** [comment]
I think I found what is causing the Show Keypad to show in the question.

The place holder should be `[[ input-number ]]` and not `[[ numeric-input ]]` for a given question.

**Comment by benjaoming** [comment]
> So, I think this can be closed now since it's functioning as it should.

:+1: Another reason being that this is upstream data, so should be fixed through KhanAcademy.org.
