### ISSUE TITLE
Topic for Chapter 1 under Grade 6 (NCERT) is missing from the content database

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/ka-lite#5121]
## Summary
The chapter 1 under Grade 6 (NCERT) is not showing up in topic tree. Under Grade 6 (NCERT) the first chapter should be "Knowing your Numbers" instead it starts from chapter 2 whole Number.

 This chapter is available in "khanacademy.org".

## Branch or installer method

 OS: Ubuntu version 14.04 LTS
Installer: "pip install ka-lite" and "sudo kalite manage setup"
Version: 0.16.5
assessment file: en.zip

## How to reproduce

1. Click on Math in topic tree.
2. Navigate to Grade (NCERT) and click on it.
3. You will observe that chapter 1 is missing.

## Screenshots
![screen shot 2016-05-17 at 9 00 20 pm](https://cloud.githubusercontent.com/assets/13453618/15328553/e3309a6c-1c72-11e6-991d-fea85d1ff0fd.png)

**Comment by benjaoming** [comment]
Confirming that it's missing and it's not because it doesn't have content.

![screenshot from 2016-05-25 11 31 39](https://cloud.githubusercontent.com/assets/374612/15535219/b04aef1c-226c-11e6-946a-c7c34fc016ab.png)

The who topic is missing in the SQLite database:

![screenshot from 2016-05-25 11 36 11](https://cloud.githubusercontent.com/assets/374612/15535282/e66d248e-226c-11e6-88e5-79d61bb307c4.png)

**Comment by benjaoming** [comment]
@aronasorman I'm assigning you for advice on why this Topic isn't in the content db?

**Comment by aronasorman** [comment]
Hi @harishbalachandran,

Thanks for reporting this! My initial hypothesis is that we just happen to have frozen the english content pack right before KA added this topic -- but that doesn't seem to be the case, since installing the bleeding edge [content pack](http://dungeon.learningequality.org/artifact/CP-KL/shared/build-179/English-content-pack/en.zip) still doesn't resolve this.

I'm looking into this further today, and see why the said topic isn't getting added in the final content pack.

**Comment by aronasorman** [comment]
Interesting, looks like Khan Academy never returns that specific topic on their API at all! I'll contact Khan Academy and ask why that is the case. I'll update this thread once I get in touch with them.

**Comment by benjaoming** [comment]
@aronasorman Great that you've investigated this! Since this is an upstream bug, I believe the action that needs taking is the action you've already taken.

Let's hope they fix it :)

@harishbalachandran thanks for reporting, closing this now, hoping that Aron's email will reach KA.org in good hands.
