### ISSUE TITLE
Missing [[ radio ]] placeholder in exercise questions with radio buttons

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5172]
## Summary

@aronasorman wrote in #5131

> I've tested a locally built content pack and most of the problem questions seem to be gone now! However, there still are a few questions that don't show answer areas. This time, they seem to be focused on True/False questions. Here's an example I found:
> 
> http://127.0.0.1:8008/learn/khan/humanities/us-history/road-to-revolution/declaration-of-independence/aspen-us-declaration-of-independence-quiz/
## Branch or installer method
- Branch: 0.16.x
## Screenshots

![screenshot from 2016-06-17 22 53 22](https://cloud.githubusercontent.com/assets/374612/16164459/8fe23f94-34de-11e6-95fa-65ec7ecd41e9.png)
## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

We still don't know the count of affected questions.

**Comment by benjaoming** [comment]
I'm afraid this issue is not seeing enough progress to be fixed in a 0.16 patch release, let's postpone it for 0.17.

The vast amount of exercises have already been fixed, so it's okay to relax and enjoy that, too :)

**Comment by benjaoming** [comment]
Same exercise, still reproducing

**Comment by benjaoming** [comment]
This question works:

![screenshot from 2017-04-07 16-34-27](https://cloud.githubusercontent.com/assets/374612/24804890/3629762a-1bb0-11e7-8f62-4b3d592c61f2.png)

And this, mysteriously doesn't:

![screenshot from 2017-04-07 16-34-59](https://cloud.githubusercontent.com/assets/374612/24804903/3a9108a4-1bb0-11e7-85b0-d2a8e48f096b.png)

**Comment by mrpau-eugene** [comment]
Hi @benjaoming it seems like this issue is not just about True/False questions. I looked at the JSON data for each question that isn't generating properly. This is just a hunch, but maybe there was a problem while generating these JSON data. In addition, as far as I have observed, most question that don't generate/display correctly has an author_name ['James Lewis']

This question is a a multiple choice kind

pk: 7477
id: x5cea7a853e9aa640
![screen shot 2017-05-03 at 5 43 12 pm](https://cloud.githubusercontent.com/assets/27984604/25655704/71a5f930-3028-11e7-9f89-5b815adcf089.png)

{"hints":[{"content":"In the 18th century, many Americans were influenced by the ideas of the Enlightenment. One movement that grew out of the Enlightenment was Deism. Deists did not ascribe to the specific beliefs of religious groups of their time and believed that while God had created the universe, He also did not interfere in human affairs. \n\n[See this video to review these ideas] /learn/khan/humanities/us-history/road-to-revolution/declaration-of-independence/life-liberty-and-the-pursuit-of-happiness/"}],"question":{"content":"**Deists…** ","widgets":{"radio 1":{"type":"radio","options":{"choices":[{"content":"pushed for the establishment of a state-supported church. ","correct":false},{"content":"believed in a Creator, but did not hold to a specific religious dogma. ","correct":true},{"content":"believed that the Declaration should not refer to a God of any sort.","correct":false},{"content":"were banned in the 13 colonies. ","correct":false}],"randomize":true}}}},"answerArea":{"type":"radio","options":{"choices":[{"content":"pushed for the establishment of a state-supported church. ","correct":false},{"content":"believed in a Creator, but did not hold to a specific religious dogma. ","correct":true},{"content":"believed that the Declaration should not refer to a God of any sort.","correct":false},{"content":"were banned in the 13 colonies. ","correct":false}],"randomize":true}}}

and it displays this

![screen shot 2017-05-03 at 5 43 12 pm 2](https://cloud.githubusercontent.com/assets/27984604/25655733/8e080032-3028-11e7-81fe-482db3ca9fc7.png)

**Comment by mrpau-eugene** [comment]
Here is another one that isn't a True/False question. 

pk: 20744
id: x699f189dd5bcc110

{"hints":[{"content":"The authors of the Declaration struck a balance in their justification of natural rights. Their explanations looked to both self-evident truths discerned by human reason and the fact that the Creator was the source of these rights. The authors refer to these rights as unalienable which means that no king or government could ever legitimately violate them. \n\n[Watch this video to review these ideas] /learn/khan/humanities/us-history/road-to-revolution/declaration-of-independence/life-liberty-and-the-pursuit-of-happiness/\n\n "}],"question":{"content":"\"endowed by their Creator with certain unalienable rights\" \n\n**This above phrase reflects the authors of the Declaration's belief that**\n\n","widgets":{"radio 1":{"type":"radio","options":{"choices":[{"content":"kings ought to have absolute power since they ruled by divine right.","correct":false},{"content":"all people enjoyed certain rights which could never legitimately be taken away from them. ","correct":true},{"content":"there should be no separation between church and state in their new country. ","correct":false},{"correct":false,"content":"that people should enjoy absolute freedom to do as they pleased in their new country. "}],"randomize":true}}}},"answerArea":{"type":"radio","options":{"choices":[{"correct":false,"content":"kings ought to have absolute power since they ruled by divine right."},{"content":"all people enjoyed certain rights which could never legitimately be taken away from them. ","correct":true},{"content":"there should be no separation between church and state in their new country. ","correct":false},{"content":"that people should enjoy absolute freedom to do as they pleased in their new country. ","correct":false}],"randomize":true}}}

![screen shot 2017-05-03 at 5 50 40 pm 2](https://cloud.githubusercontent.com/assets/27984604/25655892/387cffc2-3029-11e7-8829-035d4aaf454c.png)

![screen shot 2017-05-03 at 5 50 40 pm](https://cloud.githubusercontent.com/assets/27984604/25655913/50295c7e-3029-11e7-85e5-cf5237799d9b.png)


Dropdown type of questions seem to generate fine.

![screen shot 2017-05-03 at 5 53 50 pm 2](https://cloud.githubusercontent.com/assets/27984604/25655956/7df79918-3029-11e7-9e4e-8a9800b626d8.png)

**Comment by benjaoming** [comment]
@mrpau-eugene you can manipulate the exercise data directly in `~/.kalite/database/content_khan_en.sqlite` to see if you can pinpoint the problem through the JSON data?

For the record (because I haven't made note of it anywhere else): This error doesn't seem to give a javascript exception or traceback.

**Comment by mrpau-eugene** [comment]
@benjaoming okay. will try to see if I the culprit is really in the JSON data

**Comment by mrpau-eugene** [comment]
@benjaoming I think this piece of text that is highlighted is required for the questions to display correctly. After adding this line, it works fine 🤣 

![screen shot 2017-05-04 at 8 41 04 am](https://cloud.githubusercontent.com/assets/27984604/25687065/bfa9d304-30a5-11e7-9ead-478101387ae9.png)

Working:

![screen shot 2017-05-04 at 8 42 32 am](https://cloud.githubusercontent.com/assets/27984604/25687067/c6e7a3d0-30a5-11e7-9006-6baea7feeaae.png)

**Comment by benjaoming** [comment]
Great find @mrpau-eugene !

Let's ask @rtibbles what he thinks about the solution. Is this because of an error in upstream data, an old version of Perseus or should we try sanitizing these data in the ka-lite-content-packs?

**Comment by rtibbles** [comment]
It is the `[[ radio 1]] ` that is vital to proper rendering, this is what indicates that the radio boxes should be present.

This looks like an upstream data issue, but you can double check by looking at the item data on Khan Academy at http://www.khanacademy.org/api/internal/assessment_items/<itemid>

**Comment by benjaoming** [comment]
> http://www.khanacademy.org/api/internal/assessment_items/

@rtibbles :arrow_up: is a 404

@mrpau-eugene can you see if the broken questions work here? -> https://www.khanacademy.org/humanities/ap-us-history/period-3/apush-declaration-of-independence/e/aspen-us-declaration-of-independence-quiz

**Comment by rtibbles** [comment]
Oh, my <item_id> addendum disappeared.

http://www.khanacademy.org/api/internal/assessment_items/x699f189dd5bcc110

**Comment by rtibbles** [comment]
Seems like the `[[ radio 1]]` is missing in the source data above too.

**Comment by benjaoming** [comment]
@rtibbles is there advice for @mrpau-eugene about how to report the issue upstream? I guess we don't want to fix such issues in ka-lite-content-packs...

**Comment by rtibbles** [comment]
My guess would be that this might be flagged to not be shown on the main KA site, so if you can't see it there, it may be that we shouldn't be downloading it.

**Comment by benjaoming** [comment]
@mrpau-eugene worth investigating if we are including questions that should be skipped because they are flagged as @rtibbles suggests they *might* be.

In case they are flagged, we would have to check up on whether the ka-lite-content-packs is properly skipping these exercise questions and whether we have to build a new English content pack for that reason.

**Comment by mrpau-eugene** [comment]
@benjaoming @rtibbles 
It seems like they aren't flagged as a question to be skipped in the main site as shown here

![screen shot 2017-05-05 at 8 45 29 am](https://cloud.githubusercontent.com/assets/27984604/25730431/4cb6bb6c-316f-11e7-9887-67dc8c35f50f.png)

I kinda don't understand but the placeholder has a value of 2. Can someone explain to me what these _values_ are for? For clarification.

[[☃  radio 2]]

![screen shot 2017-05-05 at 8 48 41 am](https://cloud.githubusercontent.com/assets/27984604/25730477/aad564d2-316f-11e7-8d57-639d602dcb3e.png)

**Comment by benjaoming** [comment]
@mrpau-eugene what's the diff between the KA.org JSON data for the above question, and the JSON data found in the KA Lite content database?

**Comment by mrpau-eugene** [comment]
@benjaoming aside from the missing [[\u2603 radio 2]], JSON data coming from **KhanAcademy**:

The widgets contains this **two** objects
"wdigets": {"radio 1": {....}, "radio 2":{...}} while the contents from the KA Lite content database only has "widgets":{"radio 1": {...}}

also, the "answerArea" object coming from KhanAcademy website contains only contains these:
![screen shot 2017-05-05 at 8 40 10 pm 1](https://cloud.githubusercontent.com/assets/27984604/25745778/2959946e-31d3-11e7-93ce-1ff45170429c.png)

while the contents in the KA Lite Database contains:
![screen shot 2017-05-05 at 8 40 26 pm](https://cloud.githubusercontent.com/assets/27984604/25745795/3b5f7444-31d3-11e7-903b-7a6719e7aee6.png)

**Comment by benjaoming** [comment]
@mrpau-eduard I'm getting a feeling that it's worth seeing if this issue and the data in our content database can be made to match what's on KA.org by building a new English content pack `en-zip`, at least for further investigation. Perhaps ask @mrpau-eduard to build it so you can see if this will correct the issue somehow?

As you can see, it was reported on Jun 17, 2016 - so it has persisted several of our content packs.

**Comment by mrpau-eugene** [comment]
@benjaoming okay thanks for the suggestion :) I'll do some more investigations, too. I'll also talk to @mrpau-eduard regarding about this.

**Comment by mrpau-eugene** [comment]
@benjaoming @mrpau-eduard I would just like to take note here that this question has been removed from Khan Academy and confirmed that it no longer exists in the newly built content packs.

**Comment by benjaoming** [comment]
Nice find @mrpau-eugene ! I'm closing this now, just added a release note about.
