### ISSUE TITLE
Updating kalite from v0.15.1 to latest version

### ISSUE THREAD

**Issue by elvistek** [learningequality/ka-lite#5187]
## Summary 

Hello @benjaoming, 

I have been working with the deployment for kalite on raspberry pi in Honduras and had already sent an installation but we cannot let it recognize videos. It is version 0.15.1. I am working with them to update it to version 0.16.5 but it does not update. 

Can I update directly from v0.15.1 to latest version or I would have to download and install latest version. This way I can be able to run the new commands to retrieve language packages as this command is not working on the old version. Help appreciated. 

## Branch or installer method

raspberry pi 3

 - Installer: Raspbian
 - Version: 0.15.1

**Comment by benjaoming** [comment]
Hi @elvistek 

Sorry but I have a lot of development work, too, so I can't really do support. Our Github issue board is intended for actual problems, bug fixes and new feature implementations.

To get help, please write support@learningequality.org -- and since your problem is slightly technical, I think you should be able to get away with raising the question on the dev mailing list:

https://groups.google.com/a/learningequality.org/forum/#!forum/dev

Best,
Ben
