### ISSUE TITLE
download videos It gets stuck

### ISSUE THREAD

**Issue by johnfelipe** [learningequality/ka-lite#5197]
hi my mates
I have 0.16.6 and i want download all video with chrome, but i have cancel downloads of videos 3 times, because It gets stuck, when do download again, begin again, this process is normal?
![other](https://cloud.githubusercontent.com/assets/428820/16662987/e882b2d0-443f-11e6-83bf-d0baba6eb80e.png)
if a cancel and rebegin that is not a problem, that videos It gets stuck, i loose it?
![kalitevideo](https://cloud.githubusercontent.com/assets/428820/16662985/e87317f8-443f-11e6-89b8-e5a979115c51.png)

I view with download video process in google chrome every 2 hours gets stuck, that videos loose or how can test that?

**Comment by benjaoming** [comment]
Hi @johnfelipe -- you've deleted the original issue template. Please dump the `server.log` file. In case you're on Windows, the file doesn't exist (because of another bug), but then try running KA Lite from command line, for instance `kalite start --foreground` and dump details of the output in the issue.

Also of interest: #4907 -- a new feature we hope to have integrated at some point.

You should also make note of your own internet connection at the point when downloads are stuck.

But the contents of the log are the most important, if you get back with that, we might be able to help you.

**Comment by benjaoming** [comment]
...on a related note, 0.16.7 will use the latest `requests` library for downloading rather than `urllib`, it would be great if you could try for instance the beta version.

You've deleted the original issue template, so I have to ask: Are you using Windows, OSX or Linux (Deb/Ubuntu)?

**Comment by benjaoming** [comment]
Disregard that, 0.16.6 was the initial release with the latest `requests` library for downloading so that isn't work investigating anyways.

**Comment by benjaoming** [comment]
Hi @johnfelipe - thanks for writing regarding the download problems, I will close this issue now because we're going to have to work on a new scheduler for this to work - see #4907 

Meanwhile, if it's possible for you, I would recommend fetching videos through the torrent files with resized videos - it's faster and more reliable: http://pantry.learningequality.org/downloads/ka-lite/0.16/content/
