### ISSUE TITLE
Indicate duration of video scan

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5200]
Since it takes 10+ hours to scan a full download of all videos, we should indicate this in the docs.

Even better, optimize the scanning function so it doesn't take 10+ hours.

**Comment by kenny55d** [comment]
The 10 hour figure doesn't apply to all hardware; I've found that it only takes about that long on the raspberry Pi2 and Pi3, which are the least powered devices I've ever run ka-lite 0.16.x on. 

I guess it's down to processing, ram and perhaps storage I/O speeds, so that figure drops significantly, the more powerful the device.

**Comment by jamalex** [comment]
@rtibbles and I got as far as narrowing this down to some very weird issues in peewee, when writing to the database (and doing some recursive tree updates). We must be able to knock it down further -- I may take a stab at it later today.

**Comment by spatiald** [comment]
FYI On our [RACHEL-Plus](https://racheloffline.org/), it takes about 5-6 hours.

Proc: Intel Atom Processor E3815, 1.46GHz
Mem: 2GB DDR3L-1067
Drive: 8GB eMMC

**Comment by jamalex** [comment]
I've got some changes in the works that (on my computer) speed things up around 9x. Still doing some testing, and will open a PR soon. Hopefully can go into a 0.16.8 patch release sometime this month.

**Comment by jamalex** [comment]
On my laptop, with the full set of videos:

- Old code: 1 hour 8 min
- New code: 6 mins 24 seconds

So, the speedup looks to be around 10x. I'll open a PR.

**Comment by spatiald** [comment]
That's amazing...look forward to testing. Thanks!

On Jul 11, 2016, at 01:21, Jamie Alexandre <notifications@github.com> wrote:

On my laptop, with the full set of videos:

   - Old code: 1 hour 8 min
   - New code: 6 mins 24 seconds

So, the speedup looks to be around 10x. I'll open a PR.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/learningequality/ka-lite/issues/5200#issuecomment-231644452>,
or mute the thread
<https://github.com/notifications/unsubscribe/AFfEa4YJS1bVYHZDoicnOYZMZPV8t020ks5qUdLpgaJpZM4JI3pO>
.

**Comment by jamalex** [comment]
The changes are now in place in #5201.

If anyone wants to test this out prior to the prerelease, you can try temporarily replacing `kalite/topic_tools/content_models.py` with the contents of:
https://raw.githubusercontent.com/jamalex/ka-lite/b819a015cec8b0c76ec1dcfa1ae466bed98c6be7/kalite/topic_tools/content_models.py

**Comment by kenny55d** [comment]
Just tested the new code on my laptop (i5 CPU 2.50GHz, 4GB RAM) with 36GB of videos and the scan completed in just 6 minutes. 
This would previously have taken 45 to 60 minutes,
massive improvement, well done!

I will test it on less powerful devices RPi2/RPi3 and post the results. Thank you.

**Comment by kenny55d** [comment]
Tested the new code on RPi3 with the full set of videos (about 36GB) and it took 45 minutes to complete video scan. Excellent result!

**Comment by benjaoming** [comment]
Fixed in #5210
