### ISSUE TITLE
Remove narratives.yml

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5282]
## Summary

Somehow we have a yml file that gets converted to a json file in order to output DOM paths and strings through an API view to a JS function.

And because of this we also have hacked `makemessages` to pick up stuff from said yml file.

@aronasorman - any reason behind this design decision or may I trump what seems to be over-complication so we can get rid of yml stuff and half of the customized `makemessages` command.

( I'm looking into it because of moving "data files" to "package data" )

## System information

 - Version: 0.17

**Comment by aronasorman** [comment]
I think we dump it out to json at some point. That yml file is for the
inline help functionality that @MCGallaspy implemented.

If you can commit the json, then just have the code read that, that should
remove the need for the yml file.

We still need them translated though, so I don’t think we can delete the
code. What do you think about making our own makemessages command, that
then calls out to the default makemessages after doing some of the custom
logic we added?


On September 20, 2016 at 05:48:15, Benjamin Bach (notifications@github.com)
wrote:

Summary

Somehow we have a yml file that gets converted to a json file in order to
output DOM paths and strings through an API view to a JS function.

And because of this we also have hacked makemessages to pick up stuff from
said yml file.

@aronasorman <https://github.com/aronasorman> - any reason behind this
design decision or may I trump what seems to be over-complication so we can
get rid of yml stuff and half of the customized makemessages command.

( I'm looking into it because of moving "data files" to "package data" )
System information

   - Version: 0.17

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/learningequality/ka-lite/issues/5282>, or mute the
thread

**Comment by benjaoming** [comment]
Oh yeah but I'll remove the json file as well :) Everything can just be put in a Python dict, no need to parse files...

**Comment by benjaoming** [comment]
Fixed in #5285

@aronasorman - I've refactored it into Python dict with `ugettext`.
