### ISSUE TITLE
KA Lite not running after update to macOS Sierra.

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5333]
## Summary

Reminder for the issue reported on info mailing list, and replicated by the team.

`Unclean shutdown` error message raises the head again!

## System information

 - Operating system: macOS Sierra
 - Version: 0.16.9
 
## Screenshots

![screen_shot_2016-10-27_at_10 51 36_am](https://cloud.githubusercontent.com/assets/1457929/19930341/4e7cb566-a108-11e6-8531-28dff609b018.png)

## Real-life consequences 

All the users updating OS to Sierra on Mac

**Comment by benjaoming** [comment]
@radinamatic - could you find if there was any more info in said email, and do you have a way to test/recreate this?

**Comment by radinamatic** [comment]
Yes, I confirmed this issue on Sierra VM at the time, but the good news is that 0.17 @mrpau-richard compied today is working a-OK! 👍

**Comment by benjaoming** [comment]
Closing this the :)

**Comment by whatabearthinks** [comment]
Unfortunately, Khan Lite isn't working since my update to macOS Sierra...and I can't seem to translate what you've figured out in this topic to be the problem. All I know is that it isn't "working a-OK" on my end. I have attempted to reinstall. When that didn't work I deleted everything, including all my videos (took days to download), but that didn't work either.
<img width="686" alt="1 ka starting" src="https://cloud.githubusercontent.com/assets/24726334/21446408/b8f5a45e-c893-11e6-8cb2-e5b46a05a620.png">
<img width="343" alt="2 ka stopped" src="https://cloud.githubusercontent.com/assets/24726334/21446412/bf536eb2-c893-11e6-8c82-f92d4efce072.png">

**Comment by mrpau-richard** [comment]
@whatabearthinks the fix for this issue is not yet in release. The KA Lite OS X installer version 0.16+ will still not work with MacOS Sierra.

**Comment by whatabearthinks** [comment]
Thanks Richard! I wish I'd somehow learned this before I decided to trash everything...
If I could only get that torrent option to work...

Should I go ahead and re-download the videos/assignments, and wait for an update that could fix the issue?

**Comment by benjaoming** [comment]
Sorry about the issue @whatabearthinks - we weren't able to add this as a "Known issues" since 0.16 was out before we managed to spot the issue on Sierra.

You can get the latest prerelease with a fixed macOS/OSX installer here: #5376 

Soon, we'll get a stable release out. Thanks for your patience ;) You can reuse downloaded videos, yes. Just retain your `~/.kalite` directory or place any videos in `~/.kalite/content` after installation.

**Comment by whatabearthinks** [comment]
Alrighty. Thank you. 
I think I’m gonna need to wait for actually release due to the fact that I can’t quite decipher how to get the download and open the .deb file.

**Comment by radinamatic** [comment]
@whatabearthinks Yes, sometimes those download links can be hard to discern among the myriad in the pre-release PR... 😉 

[Mac installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMWElnUXhTNTY0SUk)
[Linux installer](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-bundle_0.17.0~b4-0ubuntu1_all.deb) - [How to install (`.deb`) file](https://ka-lite.readthedocs.io/en/latest/installguide/install_all.html#linux)

**Comment by whatabearthinks** [comment]
Thank you very much for the links.
But what are the reassurances that these downloads are secure, and free of spyware, malware, etc…? Anyone who “hacked” me wouldn’t get much, but it’d still be a major inconvenience that I’d have to deal with in the future.

**Comment by radinamatic** [comment]
We cannot offer stronger assurance from the fact that all our code is FOSS hosted here on GH repository, for all the world to see.

Once the final release is out, you will be able to download it from [learningequality.org](http://pantry.learningequality.org/downloads/ka-lite/0.17/), same as millions of our users around the globe.

**Comment by whatabearthinks** [comment]
That's great. Thank you. 
Thank you.
