### ISSUE TITLE
Topics and subtopic menus are in a different language than the rest of the menus

### ISSUE THREAD

**Issue by KevinTripp** [learningequality/ka-lite#5351]
## Summary

The home page of ka-lite is showing the content topics in a different language than the rest of the site.  The content menu mismatch hasn't changed after restarting KA-Lite, switching languages, and redownloading videos.  The error first started appearing for us around march/april 2016.

## System information

 - Operating system: Mac, Windows, Android
 - Ka-lite is run on linux, centOS 5 or 6
 - Version: 0.11.1
 - Browser: Chrome, Firefox, Safari

## How to reproduce

Sadly, I don't have steps to reproduce since we can't revert back to normal.

To view the issue:
1. Go to our instance of ka-lite
2. Look at the main content menu
3. Click through the rest of the content menus to see which ones have the wrong language and which ones are correct

To see the issue from a different frame of reference:
1. Go to our instance of ka-lite
2. Look at the main content menu, the site will be in english but the content menu won't be
3. Change the language with the picker on the upper right hand side from english to Spanish(Castillano)
4. When the page resets everything will be in Spanish as expected
5. If you click into sub-menus everything will consistently be Spanish
5. If you change the language back to English, the top two menus will still be wrong(not in English) and the rest of the submenus will be in English

## Screenshots

<img width="1181" alt="screen shot 2016-12-01 at 6 01 21 pm" src="https://cloud.githubusercontent.com/assets/2286110/20816706/ab699d98-b7f1-11e6-84d0-2012907aacfe.png">
<img width="1253" alt="screen shot 2016-12-01 at 6 01 13 pm" src="https://cloud.githubusercontent.com/assets/2286110/20816707/ab6b3324-b7f1-11e6-85aa-7b2fbd0b9abe.png">
<img width="1214" alt="screen shot 2016-12-01 at 6 00 37 pm" src="https://cloud.githubusercontent.com/assets/2286110/20816708/ab6d2832-b7f1-11e6-845f-50e9e400fecc.png">

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

This is impacting our students because it is confusing for lower literacy students to find the content the need/want to view.

**Comment by benjaoming** [comment]
Hi @KevinTripp 

Thanks for the report. Since it regards an old version, we can't really fix it anymore. It's quite complex what might be going on here.

The issue doesn't exist in later version of KA Lite.

I'm not quite sure why it would start to suddenly happen in April 2016, assuming you have installed 0.11.1 around when it was released - which is likely back in 2013.

Normally, we support an upgrade path from release to release, but it's a lot of work, so I would suggest you try out the following:

1. Install something from the current 0.16 series
1. Move your database file manually from where it is now to the new location `~/.kalite/database/data.sqlite`
1. Run `kalite manage setup` and database migrations will run. If this doesn't work, you can stop here.
1. Install languages and download videos again

A lot has changed in these versions regarding exercises and videos, so most likely the student data will pertain the wrong videos and exercises anyways. Which is why I actually think you might be better off starting a new installation from scratch.

For more help, join our community forums: http://community.learningequality.org/
