### ISSUE TITLE
kalite manage unpack_assessment_zip command gone in 0.17?

### ISSUE THREAD

**Issue by tim-moody** [learningequality/ka-lite#5417]
kalite manage unpack_assessment_zip gives "unknown command"

**Comment by rtibbles** [comment]
Yes, the assessment zips are now integrated into the content packs, and should no longer be necessary. Is it getting called somewhere, or were you just running it yourself from the command line?

**Comment by tim-moody** [comment]
It's part of the Internet in a Box playbook to download an assessment zip and load it using this command.

We don't expect the user to do any of the setup manually, so need callable scripts or commands for setup.

Can assessment items still be downloaded independently?

**Comment by tim-moody** [comment]
Thinking about this some more. Does this mean that a user can get assessment items through the management ui after kalite is setup?

what about EN? is that automatic?

**Comment by rtibbles** [comment]
The 'EN' content pack should be bundled in with any installer, so should not need to be added. 

For additional languages this should be what you are after:
`kalite manage retrievecontentpack download <lang>`.

**Comment by benjaoming** [comment]
Correct what @rtibbles is saying. Since 0.15, the unpack_assessment_items has been deprecated and was only used as an internal component in the Debian .deb installer.

Just to clarify our terminology a bit:

"content pack" = a database of translated videos+exercises, subtitles, and translation files for the interface.

"assessment items" = data files used for exercises, such as images and javascript files. These are all included in the English contentpack, `en.zip` - which is included with the installers. 

The English content pack is the only content pack that contains assessment items, and all other content packs depend on it for displaying their exercises.
