### ISSUE TITLE
Installing with Homebrew python fails

### ISSUE THREAD

**Issue by commitay** [learningequality/ka-lite#5525]
## Summary

Since https://github.com/Homebrew/homebrew-core/pull/14408, Homebrew `python` doesn't have a `/usr/local/bin/python`. This causes the `KA-Lite.pkg` install to fail.

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: macOS 10.13
 - Version: 0.17.3
 - Browser: Chrome

```
$ which -a python
/usr/bin/python

$ which -a python2
/usr/local/bin/python2
```
```
ls /usr/local/bin/ | grep -i python
python2
python2-config
python2.7
python2.7-config
pythonw2
pythonw2.7
```
#### Excerpt from README.md included in `KA-Lite-0.17.3.dmg`

```
## These are the paths used by the KA Lite installer to check the installed Python version in your system. 
* "/usr/local/bin/python"
* "which python" command will return a path of the python installed in your system.

## If your Python installed by "brew". Use "brew" also to upgrade your Python, to preserve your Python path.

```

## How to reproduce

1. `brew install python`
2. Run `KA-Lite.pkg` installer

## Screenshots

![ka lite](https://user-images.githubusercontent.com/26216252/31208773-7d83fa88-a9ca-11e7-832a-6cef43194ee8.png)

**Comment by cpauya** [comment]
Thanks for the report @commitay.  Just a reminder that KA-Lite needs Python 2.7.11+ -- so that message can also mean your Mac's Python version is not 2.7.11+.  Though I must admit that a fresh `brew install python` should've installed version higher than 2.7.11.

I just tried `python -V` on my fresh macOS High Sierra 10.13 and it shows `Python 2.7.10` (the default that comes with the OS).

To help us isolate the issue further, can you try to check the version with `python -V` or `python --version` or just run the Python interpreter so it shows the version if it meets the KA-Lite required version?

**Comment by commitay** [comment]
Sorry, I'm actually on 10.13 as well.

```
$ python --version
Python 2.7.10

$ /usr/bin/python --version
Python 2.7.10

$ python2 --version
Python 2.7.14

$/usr/local/bin/python2 --version
Python 2.7.14

```
```
$ brew info python
python: stable 2.7.14 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python/2.7.14 (3,517 files, 48.4MB) *
  Poured from bottle on 2017-10-05 at 12:10:46
```

**Comment by cpauya** [comment]
Thanks for the quick response.  These are helpful.

Yes indeed it seems the KA-Lite installer is picking-up the default macOS Python version instead of  the `brew` version.

@mrpau-richard Hopefully can take a look at this for a fix soon.  Maybe we can use `python2` instead of just `python`?

**Comment by benjaoming** [comment]
This issue was moved to learningequality/ka-lite-installers#470
