### ISSUE TITLE
Unable to download (or torrent) important Swahili videos for KA Lite

### ISSUE THREAD

**Issue by holta** [learningequality/ka-lite#5629]
Hi @aronasorman,

I'm unable to download KA Lite's compressed Swahili videos (& associated thumbnails) here:
http://pantry.learningequality.org/downloads/ka-lite/0.17/content/

Specifically:
http://pantry.learningequality.org/downloads/ka-lite/0.17/content/ka-lite-0.17-resized-videos-swahili.torrent

I've tried for 3 days now, and the 2.11GB folder doesn't even begin to download.

Since the torrent process is not working, would you be able to offer this download in some other way?  For those in Africa with very low-end machines that cannot run Kolibri, who really need this.  Thank you please for considering!

ASIDE: I spoke to @benjaoming and he very much tried to help earlier today, but was unable to find these important Swahili content files.  Thank you again for helping us with a very similar issue in September (iiab/iiab#2538).

**Comment by rtibbles** [comment]
Hi @holta,

We’ve done some investigating, and it seems that these videos are no longer hosted on our servers. It’s not entirely clear what has happened to them, and the servers that were recoding them have also been decommissioned. Unfortunately, because our focus has not been on KA Lite for many years now, and it is now fully deprecated in favor of Kolibri, we are no longer able to maintain these. We will be updating the messaging in places where we have not clearly expressed this.

Our current recommendation for serving the Swahili KA videos is to use Kolibri, which users across East Africa have done successfully. I would be interested to know the performance bottlenecks and issues you have seen with Kolibri, so that we can help to make this workable for the hardware you are deploying on. If you can give us more details, I’d be happy to offer additional solutions for improving the performance, and also factor this into prioritizing additional performance enhancements for Kolibri.

Kind regards,
Richard

**Comment by benjaoming** [comment]
Are the videos still available through the conventional download interface? They are of course in a higher resolution, but they could be re-encoded to create a new Swahili torrent with downsampled versions.

I.e. this one:

![image](https://user-images.githubusercontent.com/374612/110870504-dac1b800-82cc-11eb-995d-7bda0c09cae1.png)

**Comment by holta** [comment]
1) Miracle: After 6 days of trying, http://pantry.learningequality.org/downloads/ka-lite/0.17/content/ka-lite-0.17-resized-videos-swahili.torrent suddenly came to life and the 2.11GB in Swahili videos are now downloaded.  I have no idea who to thank, e.g. if it was someone nameless reading this ticket or otherwise, but regardless **_thank you to @rtibbles, @aronasorman, @benjaoming, @jamalex and everyone in the wider Learning Equality Community who've made this all possible._**

2) A clarification that Internet-in-a-Box is hard at work on a strategy to deliver the best of KA Lite and Kolibri to **_many millions of people, starting with those in absolute dire poverty._**  This means that KA Lite is currently far more common than Kolibri as part of this essential work in 2021, given that destitute poverty necessarily = very small microSD cards/disks + very slow CPU's + very small amounts of RAM (memory) + minimum of electricity + severe lack of teachers/trainers/etc.

3) The great news is that KA Lite (and Kolibri in wealthier communities) are both proving incredibly popular, even despite what are effectively impossible conditions.  And so we strongly welcome Learning Equality's very hard work trying to keep Kolibri relevant to the most meager platforms on earth — while understanding that miracles are not always possible — but welcoming such when they can indeed happen.

4) Finally, we can only hope that the most poverty-stricken communities on this planet somehow (more miracles please) surmount that in coming years.  Such that they might well be able to upgrade from KA Lite to Kolibri, well before the end of this decade, in most/many if not all cases.  An incredible and sometimes frightening journey we're all on here ~ together ~ please do keep in touch one & all!

http://internet-in-a-box.org

**Comment by rtibbles** [comment]
Seems like this issue is fixed, so closing.
